/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.grupo9.edext.grupo9.estacion_de_trabajo.gui.instituto;

import com.grupo9.edext.grupo9.estacion_de_trabajo.cliente.InstitutoPres;
import com.grupo9.edext.grupo9.servidor_central.dominio.DataInstituto;
import java.util.HashSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Walter
 */
public class GestionarInstitutosJInternalFrame extends javax.swing.JInternalFrame {
    private final InstitutoPres institutoPres = new InstitutoPres();

    /**
     * Creates new form GestionarInstitutosJInternalFrame
     */
    public GestionarInstitutosJInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelConsultarUsuarios1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableInstitutos = new javax.swing.JTable();
        jPanelSeccionCrearNuevoInstituto = new javax.swing.JPanel();
        jTextCrearInstituto = new javax.swing.JTextField();
        jLabelCrearInstituto = new javax.swing.JLabel();
        jLabelSeccionCrearInstituto = new javax.swing.JLabel();
        jButtonGuardarInstituto = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelSeccionListarInstituto = new javax.swing.JLabel();
        jButtonCancelarInstituto = new javax.swing.JButton();
        jButtonConsultarInstitutosRefresh = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabelConsultarUsuarios1.setText("Gestión de Institutos");

        jTableInstitutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableInstitutos);

        jLabelCrearInstituto.setText("Nombre");

        jLabelSeccionCrearInstituto.setText("Ingresar nuevo Instituto");

        jButtonGuardarInstituto.setText("Aceptar");
        jButtonGuardarInstituto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarInstitutoActionPerformed(evt);
            }
        });

        jLabelSeccionListarInstituto.setText("Lista de Institutos");

        jButtonCancelarInstituto.setText("Cancelar");
        jButtonCancelarInstituto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarInstitutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSeccionCrearNuevoInstitutoLayout = new javax.swing.GroupLayout(jPanelSeccionCrearNuevoInstituto);
        jPanelSeccionCrearNuevoInstituto.setLayout(jPanelSeccionCrearNuevoInstitutoLayout);
        jPanelSeccionCrearNuevoInstitutoLayout.setHorizontalGroup(
            jPanelSeccionCrearNuevoInstitutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addGroup(jPanelSeccionCrearNuevoInstitutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSeccionCrearNuevoInstitutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSeccionCrearNuevoInstitutoLayout.createSequentialGroup()
                        .addGroup(jPanelSeccionCrearNuevoInstitutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSeccionCrearInstituto)
                            .addComponent(jLabelSeccionListarInstituto))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelSeccionCrearNuevoInstitutoLayout.createSequentialGroup()
                        .addGroup(jPanelSeccionCrearNuevoInstitutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCrearInstituto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextCrearInstituto, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
                        .addComponent(jButtonCancelarInstituto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonGuardarInstituto)))
                .addContainerGap())
        );
        jPanelSeccionCrearNuevoInstitutoLayout.setVerticalGroup(
            jPanelSeccionCrearNuevoInstitutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSeccionCrearNuevoInstitutoLayout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSeccionCrearInstituto)
                .addGap(17, 17, 17)
                .addComponent(jLabelCrearInstituto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSeccionCrearNuevoInstitutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCrearInstituto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGuardarInstituto)
                    .addComponent(jButtonCancelarInstituto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSeccionListarInstituto)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jButtonConsultarInstitutosRefresh.setText("Refrescar");
        jButtonConsultarInstitutosRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarInstitutosRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelConsultarUsuarios1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonConsultarInstitutosRefresh)))
                .addContainerGap())
            .addComponent(jPanelSeccionCrearNuevoInstituto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelConsultarUsuarios1)
                .addGap(18, 18, 18)
                .addComponent(jPanelSeccionCrearNuevoInstituto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonConsultarInstitutosRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarInstitutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarInstitutoActionPerformed
        final String nombre = jTextCrearInstituto.getText().trim();

        if (nombre.isEmpty() || nombre.equals("")) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el nombre del instituto.", "Dato requerido", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (Boolean.TRUE.equals(institutoPres.existeInstituto(nombre))) {
            JOptionPane.showMessageDialog(this, "Ya existe un instituto con ese nombre. Prueba con otro nombre.", "Instituto duplicado", JOptionPane.WARNING_MESSAGE);
            return;
        }

        System.out.println("[GUI] Crear nuevo Instituto: " + nombre);

        boolean institutoGuardado = institutoPres.guardarNuevoInstituto(nombre);

        if (!institutoGuardado) {
            //            jLabelCrearInstitutoNombreError.setVisible(true);
            javax.swing.JOptionPane.showMessageDialog(this, "Ya existe un Instituto con ese nombre, prueba uno diferente", "Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        this.limpiarFormularioInstituto();

        javax.swing.JOptionPane.showMessageDialog(this, "Instituto registrado y guardado con éxito", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // Cargar la nueva lista y actualizar tabla
        HashSet<DataInstituto> institutos = this.institutoPres.cargarInstitutos();

        this.actualizarTablaDeInstitutos(institutos);
    }//GEN-LAST:event_jButtonGuardarInstitutoActionPerformed

    private void jButtonCancelarInstitutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarInstitutoActionPerformed
        this.limpiarFormularioInstituto();
    }//GEN-LAST:event_jButtonCancelarInstitutoActionPerformed

    private void jButtonConsultarInstitutosRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarInstitutosRefreshActionPerformed
        System.out.println("[GUI] Consultar todos los Institutos");
        HashSet<DataInstituto> institutos = this.institutoPres.cargarInstitutos();

        this.actualizarTablaDeInstitutos(institutos);
    }//GEN-LAST:event_jButtonConsultarInstitutosRefreshActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        HashSet<DataInstituto> institutos = this.institutoPres.cargarInstitutos();
        
        this.actualizarTablaDeInstitutos(institutos);
    }//GEN-LAST:event_formInternalFrameOpened

    private void actualizarTablaDeInstitutos(HashSet<DataInstituto> institutos){
        System.out.println("[GUI] Consultar todos los Institutos");

        if(institutos == null){
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTableInstitutos.getModel();
        model.setRowCount(0);

        for(DataInstituto instituto: institutos){
            Object[] programaObj = new Object[]{instituto.nombreI()};
            model.addRow(programaObj);
        }
    }
    
    private void limpiarFormularioInstituto() {
        jTextCrearInstituto.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarInstituto;
    private javax.swing.JButton jButtonConsultarInstitutosRefresh;
    private javax.swing.JButton jButtonGuardarInstituto;
    private javax.swing.JLabel jLabelConsultarUsuarios1;
    private javax.swing.JLabel jLabelCrearInstituto;
    private javax.swing.JLabel jLabelSeccionCrearInstituto;
    private javax.swing.JLabel jLabelSeccionListarInstituto;
    private javax.swing.JPanel jPanelSeccionCrearNuevoInstituto;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableInstitutos;
    private javax.swing.JTextField jTextCrearInstituto;
    // End of variables declaration//GEN-END:variables
}
