package com.grupo9.edext.grupo9.estacion_de_trabajo.gui.edicion_de_curso;

import com.grupo9.edext.grupo9.servidor_central.dominio.DataCurso;
import com.grupo9.edext.grupo9.servidor_central.dominio.DataInstituto;
import com.grupo9.edext.grupo9.servidor_central.dominio.DataDocente;
import com.grupo9.edext.grupo9.estacion_de_trabajo.cliente.EdicionCursoPres;
import com.grupo9.edext.grupo9.interfaces.IServidorCentral;
import com.grupo9.edext.grupo9.miscelanea.Fabrica;
import com.grupo9.edext.grupo9.mensajes.ErrorNoExiste;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.Set;
import javax.swing.DefaultListModel;
import java.util.LinkedHashSet;
import javax.swing.JOptionPane;

public class AltaEdicionJInternalFrame extends javax.swing.JInternalFrame {
    private DataCurso cursoSeleccionado;
    private DataInstituto instituto;
    private DataDocente[] docentes;
    private Set<DataDocente> docentesSeleccionados = new LinkedHashSet<>();
    private DefaultListModel<String> modeloDocentes;
    private final EdicionCursoPres edicionCursoPres = new EdicionCursoPres();
    private final IServidorCentral servidorCentral;
    
    public AltaEdicionJInternalFrame(DataCurso cursoSeleccionado, DataInstituto instituto) {
        initComponents();
        this.cursoSeleccionado = cursoSeleccionado;
        this.instituto = cursoSeleccionado.instituto();
        servidorCentral = Fabrica.getInstance().getIServidorCentral();
        modeloDocentes = new DefaultListModel<>();
        jListDocentes.setModel(modeloDocentes);
        jComboBoxDocenteEdicion.setPrototypeDisplayValue("XXXXXXXXXXXXXXXXXXXXXXXX");
        setTitle("Alta de Edición");
        setClosable(true);
        setResizable(true);
        setMaximizable(true);
        setIconifiable(true);
        jSpinnerEdicionFInicio.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_MONTH));
        javax.swing.JSpinner.DateEditor editor1 = new javax.swing.JSpinner.DateEditor(jSpinnerEdicionFInicio, "dd/MM/yyyy");
        jSpinnerEdicionFInicio.setEditor(editor1);
        jSpinnerEdicionFFin.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_MONTH));
        javax.swing.JSpinner.DateEditor editor2 = new javax.swing.JSpinner.DateEditor(jSpinnerEdicionFFin, "dd/MM/yyyy");
        jSpinnerEdicionFFin.setEditor(editor2);
        cargarDocentes();
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAltaEdicion = new javax.swing.JLabel();
        jLabelEdicionNombre = new javax.swing.JLabel();
        jTextEdicionNombre = new javax.swing.JTextField();
        jLabelEdicionDocente = new javax.swing.JLabel();
        jLabelEdicionFInicio = new javax.swing.JLabel();
        jSpinnerEdicionFInicio = new javax.swing.JSpinner();
        jLabelEdicionFFin = new javax.swing.JLabel();
        jSpinnerEdicionFFin = new javax.swing.JSpinner();
        jLabelEdicionCupo = new javax.swing.JLabel();
        jTextEdicionCupo = new javax.swing.JTextField();
        jButtonGuardarEdicion = new javax.swing.JButton();
        jComboBoxDocenteEdicion = new javax.swing.JComboBox<>();
        jLabelDocentesAgregados = new javax.swing.JLabel();
        jButtonAgregarDocente = new javax.swing.JButton();
        jScrollPaneListaDocentes = new javax.swing.JScrollPane();
        jListDocentes = new javax.swing.JList<>();

        setPreferredSize(new java.awt.Dimension(380, 630));

        jLabelAltaEdicion.setText("Crear Edición");
        jLabelAltaEdicion.setMaximumSize(new java.awt.Dimension(83, 16));
        jLabelAltaEdicion.setMinimumSize(new java.awt.Dimension(83, 16));
        jLabelAltaEdicion.setName(""); // NOI18N
        jLabelAltaEdicion.setPreferredSize(new java.awt.Dimension(83, 16));

        jLabelEdicionNombre.setText("Nombre");

        jLabelEdicionDocente.setText("Docente");

        jLabelEdicionFInicio.setText("Fecha Inicio");

        jLabelEdicionFFin.setText("Fecha Fin");

        jLabelEdicionCupo.setText("Cupo");

        jTextEdicionCupo.setColumns(4);

        jButtonGuardarEdicion.setText("Guardar");
        jButtonGuardarEdicion.addActionListener(this::jButtonGuardarEdicionActionPerformed);

        jLabelDocentesAgregados.setText("Docentes agregados");

        jButtonAgregarDocente.setText("Agregar");
        jButtonAgregarDocente.addActionListener(this::jButtonAgregarDocenteActionPerformed);

        jListDocentes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneListaDocentes.setViewportView(jListDocentes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonGuardarEdicion))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextEdicionNombre)
                                    .addComponent(jComboBoxDocenteEdicion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSpinnerEdicionFFin)
                                    .addComponent(jTextEdicionCupo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelEdicionCupo)
                                            .addComponent(jLabelEdicionFFin)
                                            .addComponent(jLabelEdicionFInicio)
                                            .addComponent(jLabelDocentesAgregados)
                                            .addComponent(jLabelEdicionDocente)
                                            .addComponent(jLabelEdicionNombre)
                                            .addComponent(jLabelAltaEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 142, Short.MAX_VALUE))
                                    .addComponent(jScrollPaneListaDocentes))
                                .addGap(31, 31, 31)
                                .addComponent(jButtonAgregarDocente)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSpinnerEdicionFInicio)
                        .addGap(113, 113, 113))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAltaEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelEdicionNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextEdicionNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelEdicionDocente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDocenteEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgregarDocente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelDocentesAgregados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneListaDocentes, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabelEdicionFInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerEdicionFInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelEdicionFFin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerEdicionFFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelEdicionCupo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextEdicionCupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonGuardarEdicion)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void cargarDocentes() {
        docentes = edicionCursoPres.traerDocentes(instituto);
        //docente obligatorio
        jComboBoxDocenteEdicion.removeAllItems();
        if (docentes != null) {
            for (DataDocente docente : docentes) {
                String nombreCompleto = docente.getNombre() + " " + docente.getApellido();
                jComboBoxDocenteEdicion.addItem(nombreCompleto);
            }
        }
    }
    
    private void actualizarListaDocentes() {
        modeloDocentes.clear();
        for (DataDocente docente : docentesSeleccionados) {
            String nombreCompleto = docente.getNombre() + " " + docente.getApellido();
            modeloDocentes.addElement(nombreCompleto);
        }
    }
    
    private void jButtonGuardarEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarEdicionActionPerformed
        String nombreEdi = jTextEdicionNombre.getText().trim();
        String textoCupo = jTextEdicionCupo.getText().trim();
        Integer cupo = null;
        //sobre el nombre
        if(nombreEdi.isBlank()){
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre.", "Datos requeridos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //sobre el cupo
        if (!textoCupo.isEmpty()) {
            try {
                cupo = Integer.parseInt(textoCupo);
                if (cupo < 0) {
                    JOptionPane.showMessageDialog(this, "Cupo negativo.", "Datos inválidos", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Cupo debe ser un número.", "Datos inválidos", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        
        //sobre el docente
        if (docentesSeleccionados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar al menos un docente.", "Datos requeridos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //sobre la fecha
        Date fecha0 = (Date) jSpinnerEdicionFInicio.getValue();
        LocalDate fechaInicio = fecha0.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        Date fecha1 = (Date) jSpinnerEdicionFFin.getValue();
        LocalDate fechaFin = fecha1.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        if (fechaInicio.isBefore(LocalDate.now())) {
            JOptionPane.showMessageDialog(this, "La fecha no debe ser anterior a la actual.", "Datos inválidos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (fechaFin.isBefore(fechaInicio)) {
            JOptionPane.showMessageDialog(this, "La fecha de finalización debe ser actual o posterior a la inicial.", "Datos inválidos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //sobre el ingreso
        try {
            servidorCentral.consultarUnaEdicionCurso(nombreEdi);
            JOptionPane.showMessageDialog(this, "Ya existe una edición con ese nombre.", "Edición duplicada", JOptionPane.WARNING_MESSAGE);
        } catch (ErrorNoExiste e) {
            System.out.println("[GUI] Crear nueva Edición: " + nombreEdi);
            System.out.println("[GUI] De curso: " + cursoSeleccionado.nombreCurso());
            System.out.println("[GUI] Fecha de inicio: " + fecha0);
            System.out.println("[GUI] Fecha de finalización: " + fecha1);
            System.out.println("[GUI] Docente(s): " + docentesSeleccionados);

            edicionCursoPres.guardarNuevaEdicion(nombreEdi, cursoSeleccionado, fechaInicio, fechaFin, cupo, docentesSeleccionados);
            JOptionPane.showMessageDialog(this, "Edición registrada y guardada con éxito!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            jTextEdicionNombre.setText("");
            jTextEdicionCupo.setText("");
            jComboBoxDocenteEdicion.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_jButtonGuardarEdicionActionPerformed

    private void jButtonAgregarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarDocenteActionPerformed
        int indiceDocente = jComboBoxDocenteEdicion.getSelectedIndex();
        if (indiceDocente == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un docente.", "Datos requeridos",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        DataDocente docente = docentes[indiceDocente];
        if (docentesSeleccionados.contains(docente)) {
            JOptionPane.showMessageDialog(this, "El docente ya fue seleccionado.", "Docente repetido",JOptionPane.WARNING_MESSAGE);
            return;
        }
        docentesSeleccionados.add(docente);
        actualizarListaDocentes();
    }//GEN-LAST:event_jButtonAgregarDocenteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarDocente;
    private javax.swing.JButton jButtonGuardarEdicion;
    private javax.swing.JComboBox<String> jComboBoxDocenteEdicion;
    private javax.swing.JLabel jLabelAltaEdicion;
    private javax.swing.JLabel jLabelDocentesAgregados;
    private javax.swing.JLabel jLabelEdicionCupo;
    private javax.swing.JLabel jLabelEdicionDocente;
    private javax.swing.JLabel jLabelEdicionFFin;
    private javax.swing.JLabel jLabelEdicionFInicio;
    private javax.swing.JLabel jLabelEdicionNombre;
    private javax.swing.JList<String> jListDocentes;
    private javax.swing.JScrollPane jScrollPaneListaDocentes;
    private javax.swing.JSpinner jSpinnerEdicionFFin;
    private javax.swing.JSpinner jSpinnerEdicionFInicio;
    private javax.swing.JTextField jTextEdicionCupo;
    private javax.swing.JTextField jTextEdicionNombre;
    // End of variables declaration//GEN-END:variables
}
