package com.grupo9.edext.grupo9.estacion_de_trabajo.gui;

import com.grupo9.edext.grupo9.servidor_central.controller.curso.Curso;
import com.grupo9.edext.grupo9.servidor_central.controller.usuario.Docente;
import com.grupo9.edext.grupo9.estacion_de_trabajo.cliente.EdicionCursoPres;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;

public class AltaEdicionJInternalFrame extends javax.swing.JInternalFrame {
    private Curso cursoSeleccionado;
    private Docente[] docentes;
    private final EdicionCursoPres edicionCursoPres = new EdicionCursoPres();
    
    public AltaEdicionJInternalFrame(Curso cursoSeleccionado) {
        initComponents();
        this.cursoSeleccionado = cursoSeleccionado;
        setTitle("Alta de Edición");
        setClosable(true);
        setResizable(true);
        jSpinnerEdicionFInicio.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_MONTH));
        javax.swing.JSpinner.DateEditor editor1 = new javax.swing.JSpinner.DateEditor(jSpinnerEdicionFInicio, "dd/MM/yyyy");
        jSpinnerEdicionFInicio.setEditor(editor1);
        jSpinnerEdicionFFin.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_MONTH));
        javax.swing.JSpinner.DateEditor editor2 = new javax.swing.JSpinner.DateEditor(jSpinnerEdicionFFin, "dd/MM/yyyy");
        jSpinnerEdicionFFin.setEditor(editor2);
        cargarDocentes();
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAltaEdicion = new javax.swing.JLabel();
        jLabelEdicionNombre = new javax.swing.JLabel();
        jTextEdicionNombre = new javax.swing.JTextField();
        jLabelEdicionDocente = new javax.swing.JLabel();
        jLabelEdicionFInicio = new javax.swing.JLabel();
        jSpinnerEdicionFInicio = new javax.swing.JSpinner();
        jLabelEdicionFFin = new javax.swing.JLabel();
        jSpinnerEdicionFFin = new javax.swing.JSpinner();
        jLabelEdicionCupo = new javax.swing.JLabel();
        jTextEdicionCupo = new javax.swing.JTextField();
        jButtonGuardarEdicion = new javax.swing.JButton();
        jComboBoxDocenteEdicion = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(380, 420));

        jLabelAltaEdicion.setText("Crear Edición");
        jLabelAltaEdicion.setMaximumSize(new java.awt.Dimension(83, 16));
        jLabelAltaEdicion.setMinimumSize(new java.awt.Dimension(83, 16));
        jLabelAltaEdicion.setName(""); // NOI18N
        jLabelAltaEdicion.setPreferredSize(new java.awt.Dimension(83, 16));

        jLabelEdicionNombre.setText("Nombre");

        jLabelEdicionDocente.setText("Docente");

        jLabelEdicionFInicio.setText("Fecha Inicio");

        jLabelEdicionFFin.setText("Fecha Fin");

        jLabelEdicionCupo.setText("Cupo");

        jTextEdicionCupo.setColumns(4);

        jButtonGuardarEdicion.setText("Guardar");
        jButtonGuardarEdicion.addActionListener(this::jButtonGuardarEdicionActionPerformed);

        jComboBoxDocenteEdicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonGuardarEdicion))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelEdicionCupo)
                            .addComponent(jSpinnerEdicionFFin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEdicionFFin)
                            .addComponent(jSpinnerEdicionFInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEdicionFInicio)
                            .addComponent(jLabelAltaEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEdicionNombre)
                            .addComponent(jLabelEdicionDocente)
                            .addComponent(jTextEdicionNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jComboBoxDocenteEdicion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextEdicionCupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 106, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAltaEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelEdicionNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextEdicionNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelEdicionDocente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxDocenteEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabelEdicionFInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerEdicionFInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelEdicionFFin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerEdicionFFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelEdicionCupo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextEdicionCupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jButtonGuardarEdicion)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void cargarDocentes() {
        docentes = edicionCursoPres.traerDocentes();
        jComboBoxDocenteEdicion.removeAllItems();
        for(Docente docente : docentes) {
            jComboBoxDocenteEdicion.addItem(docente.getNombre() + " " + docente.getApellido());
        }
    }
    
    private void jButtonGuardarEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarEdicionActionPerformed
        final String nombreEdi = jTextEdicionNombre.getText();
        final int cupo = Integer.parseInt(jTextEdicionCupo.getText());
        Date fecha0 = (Date) jSpinnerEdicionFInicio.getValue();
        LocalDate fechaInicio = fecha0.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        Date fecha1 = (Date) jSpinnerEdicionFFin.getValue();
        LocalDate fechaFin = fecha1.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        int indice = jComboBoxDocenteEdicion.getSelectedIndex();
        if(indice == -1) {
             return;
        }
        Docente docente = docentes[indice];

        System.out.println("[GUI] Crear nueva Edición: " + nombreEdi);
        System.out.println("[GUI] De curso: " + cursoSeleccionado);
        System.out.println("[GUI] Fecha de inicio: " + fecha0);
        System.out.println("[GUI] Fecha de finalización: " + fecha1);
        System.out.println("[GUI] Docente: " + docente);
        
        edicionCursoPres.guardarNuevaEdicion(nombreEdi, cursoSeleccionado, fechaInicio, fechaFin, cupo, docente);
    }//GEN-LAST:event_jButtonGuardarEdicionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardarEdicion;
    private javax.swing.JComboBox<String> jComboBoxDocenteEdicion;
    private javax.swing.JLabel jLabelAltaEdicion;
    private javax.swing.JLabel jLabelEdicionCupo;
    private javax.swing.JLabel jLabelEdicionDocente;
    private javax.swing.JLabel jLabelEdicionFFin;
    private javax.swing.JLabel jLabelEdicionFInicio;
    private javax.swing.JLabel jLabelEdicionNombre;
    private javax.swing.JSpinner jSpinnerEdicionFFin;
    private javax.swing.JSpinner jSpinnerEdicionFInicio;
    private javax.swing.JTextField jTextEdicionCupo;
    private javax.swing.JTextField jTextEdicionNombre;
    // End of variables declaration//GEN-END:variables
}
