package com.grupo9.edext.grupo9.estacion_de_trabajo.gui;

import com.grupo9.edext.grupo9.servidor_central.controller.curso.Curso;
import com.grupo9.edext.grupo9.servidor_central.controller.instituto.Instituto;
import com.grupo9.edext.grupo9.servidor_central.controller.usuario.Docente;
import com.grupo9.edext.grupo9.estacion_de_trabajo.cliente.EdicionCursoPres;
import com.grupo9.edext.grupo9.servidor_central.controller.ServidorCentralController;
import com.grupo9.edext.grupo9.mensajes.ErrorNoExiste;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.Set;
import java.util.HashSet;
import javax.swing.JOptionPane;

public class AltaEdicionJInternalFrame extends javax.swing.JInternalFrame {
    private Curso cursoSeleccionado;
    private Instituto instituto;
    private Docente[] docentes;
    private final EdicionCursoPres edicionCursoPres = new EdicionCursoPres();
    private final ServidorCentralController servidorCentral;
    
    public AltaEdicionJInternalFrame(Curso cursoSeleccionado, Instituto instituto) {
        initComponents();
        this.cursoSeleccionado = cursoSeleccionado;
        this.instituto = cursoSeleccionado.getInstituto();
        servidorCentral = ServidorCentralController.getInstance();
        setTitle("Alta de Edición");
        setClosable(true);
        setResizable(true);
        setMaximizable(true);
        setIconifiable(true);
        jSpinnerEdicionFInicio.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_MONTH));
        javax.swing.JSpinner.DateEditor editor1 = new javax.swing.JSpinner.DateEditor(jSpinnerEdicionFInicio, "dd/MM/yyyy");
        jSpinnerEdicionFInicio.setEditor(editor1);
        jSpinnerEdicionFFin.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_MONTH));
        javax.swing.JSpinner.DateEditor editor2 = new javax.swing.JSpinner.DateEditor(jSpinnerEdicionFFin, "dd/MM/yyyy");
        jSpinnerEdicionFFin.setEditor(editor2);
        cargarDocentes();
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAltaEdicion = new javax.swing.JLabel();
        jLabelEdicionNombre = new javax.swing.JLabel();
        jTextEdicionNombre = new javax.swing.JTextField();
        jLabelEdicionDocente = new javax.swing.JLabel();
        jLabelEdicionFInicio = new javax.swing.JLabel();
        jSpinnerEdicionFInicio = new javax.swing.JSpinner();
        jLabelEdicionFFin = new javax.swing.JLabel();
        jSpinnerEdicionFFin = new javax.swing.JSpinner();
        jLabelEdicionCupo = new javax.swing.JLabel();
        jTextEdicionCupo = new javax.swing.JTextField();
        jButtonGuardarEdicion = new javax.swing.JButton();
        jComboBoxDocenteEdicion = new javax.swing.JComboBox<>();
        jLabelDocenteOpEdicion = new javax.swing.JLabel();
        jComboBoxDocenteOpEdicion = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(380, 500));

        jLabelAltaEdicion.setText("Crear Edición");
        jLabelAltaEdicion.setMaximumSize(new java.awt.Dimension(83, 16));
        jLabelAltaEdicion.setMinimumSize(new java.awt.Dimension(83, 16));
        jLabelAltaEdicion.setName(""); // NOI18N
        jLabelAltaEdicion.setPreferredSize(new java.awt.Dimension(83, 16));

        jLabelEdicionNombre.setText("Nombre");

        jLabelEdicionDocente.setText("Docente 1");

        jLabelEdicionFInicio.setText("Fecha Inicio");

        jLabelEdicionFFin.setText("Fecha Fin");

        jLabelEdicionCupo.setText("Cupo");

        jTextEdicionCupo.setColumns(4);

        jButtonGuardarEdicion.setText("Guardar");
        jButtonGuardarEdicion.addActionListener(this::jButtonGuardarEdicionActionPerformed);

        jComboBoxDocenteEdicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelDocenteOpEdicion.setText("Docente 2 (Adicional)");

        jComboBoxDocenteOpEdicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonGuardarEdicion))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextEdicionNombre)
                            .addComponent(jComboBoxDocenteOpEdicion, 0, 249, Short.MAX_VALUE)
                            .addComponent(jComboBoxDocenteEdicion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinnerEdicionFInicio)
                            .addComponent(jSpinnerEdicionFFin)
                            .addComponent(jTextEdicionCupo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelEdicionCupo)
                                    .addComponent(jLabelEdicionFFin)
                                    .addComponent(jLabelEdicionFInicio)
                                    .addComponent(jLabelDocenteOpEdicion)
                                    .addComponent(jLabelEdicionDocente)
                                    .addComponent(jLabelEdicionNombre)
                                    .addComponent(jLabelAltaEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(107, 107, 107)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAltaEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelEdicionNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextEdicionNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelEdicionDocente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxDocenteEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelDocenteOpEdicion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxDocenteOpEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelEdicionFInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerEdicionFInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelEdicionFFin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerEdicionFFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabelEdicionCupo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextEdicionCupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonGuardarEdicion)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void cargarDocentes() {
        docentes = edicionCursoPres.traerDocentes(instituto);
        //docente obligatorio
        jComboBoxDocenteEdicion.removeAllItems();
        //docente adicional
        jComboBoxDocenteOpEdicion.removeAllItems();
        jComboBoxDocenteOpEdicion.addItem("Ninguno");
        if (docentes != null) {
            for (Docente docente : docentes) {
                String nombreCompleto = docente.getNombre() + " " + docente.getApellido();
                jComboBoxDocenteEdicion.addItem(nombreCompleto);
                jComboBoxDocenteOpEdicion.addItem(nombreCompleto);
            }
        }
    }
    
    private void jButtonGuardarEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarEdicionActionPerformed
        String nombreEdi = jTextEdicionNombre.getText().trim();
        String textoCupo = jTextEdicionCupo.getText().trim();
        Integer cupo = null;
        //sobre el nombre
        if(nombreEdi.isBlank()){
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre.", "Datos requeridos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //sobre el cupo
        if (!textoCupo.isEmpty()) {
            try {
                cupo = Integer.parseInt(textoCupo);
                if (cupo < 0) {
                    JOptionPane.showMessageDialog(this, "Cupo negativo.", "Datos inválidos", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Cupo debe ser un número.", "Datos inválidos", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        
        //sobre el docente
        int indiceDocente1 = jComboBoxDocenteEdicion.getSelectedIndex();
        int indiceDocente2 = jComboBoxDocenteOpEdicion.getSelectedIndex();
        if (indiceDocente1 == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar al menos un docente.", "Datos requeridos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Docente docente1 = docentes[indiceDocente1];
        Docente docente2 = null;
        
        if(indiceDocente2 > 0) {
            docente2 = docentes[indiceDocente2 - 1];
            if (docente1.equals(docente2)) {
                JOptionPane.showMessageDialog(this, "El docente ya fue seleccionado.", "Datos inválidos", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        
        Set<Docente> docentesSeleccionados = new HashSet<>();
        docentesSeleccionados.add(docente1);
        if(docente2 != null) {
            docentesSeleccionados.add(docente2);
        }
        
        //sobre la fecha
        Date fecha0 = (Date) jSpinnerEdicionFInicio.getValue();
        LocalDate fechaInicio = fecha0.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        Date fecha1 = (Date) jSpinnerEdicionFFin.getValue();
        LocalDate fechaFin = fecha1.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        if (fechaInicio.isBefore(LocalDate.now())) {
            JOptionPane.showMessageDialog(this, "La fecha no debe ser anterior a la actual.", "Datos inválidos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (fechaFin.isBefore(fechaInicio)) {
            JOptionPane.showMessageDialog(this, "La fecha de finalización debe ser actual o posterior a la inicial.", "Datos inválidos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //sobre el ingreso
        try {
            servidorCentral.consultarUnaEdicionCurso(nombreEdi);
            JOptionPane.showMessageDialog(this, "Ya existe una edición con ese nombre.", "Edición duplicada", JOptionPane.WARNING_MESSAGE);
        } catch (ErrorNoExiste e) {
            System.out.println("[GUI] Crear nueva Edición: " + nombreEdi);
            System.out.println("[GUI] De curso: " + cursoSeleccionado);
            System.out.println("[GUI] Fecha de inicio: " + fecha0);
            System.out.println("[GUI] Fecha de finalización: " + fecha1);
            System.out.println("[GUI] Docente(s): " + docentesSeleccionados);

            edicionCursoPres.guardarNuevaEdicion(nombreEdi, cursoSeleccionado, fechaInicio, fechaFin, cupo, docentesSeleccionados);
            JOptionPane.showMessageDialog(this, "Edición registrada y guardada con éxito!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            jTextEdicionNombre.setText("");
            jTextEdicionCupo.setText("");
            jComboBoxDocenteEdicion.setSelectedIndex(-1);
            jComboBoxDocenteOpEdicion.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jButtonGuardarEdicionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardarEdicion;
    private javax.swing.JComboBox<String> jComboBoxDocenteEdicion;
    private javax.swing.JComboBox<String> jComboBoxDocenteOpEdicion;
    private javax.swing.JLabel jLabelAltaEdicion;
    private javax.swing.JLabel jLabelDocenteOpEdicion;
    private javax.swing.JLabel jLabelEdicionCupo;
    private javax.swing.JLabel jLabelEdicionDocente;
    private javax.swing.JLabel jLabelEdicionFFin;
    private javax.swing.JLabel jLabelEdicionFInicio;
    private javax.swing.JLabel jLabelEdicionNombre;
    private javax.swing.JSpinner jSpinnerEdicionFFin;
    private javax.swing.JSpinner jSpinnerEdicionFInicio;
    private javax.swing.JTextField jTextEdicionCupo;
    private javax.swing.JTextField jTextEdicionNombre;
    // End of variables declaration//GEN-END:variables
}
