package com.grupo9.edext.grupo9.estacion_de_trabajo.gui;

import com.grupo9.edext.grupo9.estacion_de_trabajo.cliente.EdicionCursoPres;
import com.grupo9.edext.grupo9.servidor_central.controller.curso.Curso;
import com.grupo9.edext.grupo9.servidor_central.controller.edicion_de_curso.EdicionCurso;
import com.grupo9.edext.grupo9.servidor_central.dominio.DataEstudiante;
import com.grupo9.edext.grupo9.servidor_central.dominio.DataEdicionCurso;
import com.grupo9.edext.grupo9.servidor_central.dominio.DataInscEdicion;
import com.grupo9.edext.grupo9.servidor_central.dominio.DataDocente;
import com.grupo9.edext.grupo9.mensajes.ErrorNoExiste;
import javax.swing.*;
import java.awt.Dimension;

public class ConsultarEdicionJInternalFrame extends javax.swing.JInternalFrame {
    private Curso cursoSeleccionado;
    private DataEdicionCurso edicion;
    private EdicionCurso[] ediciones;
    private final EdicionCursoPres edicionCursoPres = new EdicionCursoPres();
    
    public ConsultarEdicionJInternalFrame(Curso cursoSeleccionado) {
        initComponents();
        this.cursoSeleccionado = cursoSeleccionado;
        setTitle("Consultar");
        setClosable(true);
        setResizable(true);
        setMaximizable(true);
        setIconifiable(true);
        cargarEdiciones();  
        noEditable();
        ocultarDatos();
        jScrollPaneEstudiantes.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
    }
    
    private void noEditable(){
        jTextFieldNombre.setEditable(false);
        jTextFieldCurso.setEditable(false);
        jTextFieldFechaInicio.setEditable(false);
        jTextFieldFechaFin.setEditable(false);
        jTextFieldDocente.setEditable(false);
        jTextFieldCupo.setEditable(false);
    }
    
    private void mostrarDatos() {
        jLabelNombre.setVisible(true);
        jTextFieldNombre.setVisible(true);
        jLabelCurso.setVisible(true);
        jTextFieldCurso.setVisible(true);
        jLabelFechaInicio.setVisible(true);
        jTextFieldFechaInicio.setVisible(true);
        jLabelFechaFin.setVisible(true);
        jTextFieldFechaFin.setVisible(true);
        jLabelDocente.setVisible(true);
        jTextFieldDocente.setVisible(true);
        jLabelEstudiantes.setVisible(true);
        jScrollPaneEstudiantes.setVisible(true);
        jLabelCupo.setVisible(true);
        jTextFieldCupo.setVisible(true);
    }
    
    private void ocultarDatos() {
        jLabelNombre.setVisible(false);
        jTextFieldNombre.setVisible(false);
        jLabelCurso.setVisible(false);
        jTextFieldCurso.setVisible(false);
        jLabelFechaInicio.setVisible(false);
        jTextFieldFechaInicio.setVisible(false);
        jLabelFechaFin.setVisible(false);
        jTextFieldFechaFin.setVisible(false);
        jLabelDocente.setVisible(false);
        jTextFieldDocente.setVisible(false);
        jLabelEstudiantes.setVisible(false);
        jScrollPaneEstudiantes.setVisible(false);
        jLabelCupo.setVisible(false);
        jTextFieldCupo.setVisible(false);
    }
    
    private void cargarEdiciones() {
        ediciones = edicionCursoPres.traerEdiciones(cursoSeleccionado);
        jComboBoxEdiciones.removeAllItems();
        for (EdicionCurso ed : ediciones) {
            jComboBoxEdiciones.addItem(ed.getNombreEdi());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEdicionNombre = new javax.swing.JLabel();
        jComboBoxEdiciones = new javax.swing.JComboBox<>();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelCurso = new javax.swing.JLabel();
        jTextFieldCurso = new javax.swing.JTextField();
        jLabelFechaFin = new javax.swing.JLabel();
        jLabelFechaInicio = new javax.swing.JLabel();
        jLabelDocente = new javax.swing.JLabel();
        jLabelEstudiantes = new javax.swing.JLabel();
        jTextFieldDocente = new javax.swing.JTextField();
        jScrollPaneEstudiantes = new javax.swing.JScrollPane();
        jListEstudiantes = new javax.swing.JList<>();
        jTextFieldFechaInicio = new javax.swing.JTextField();
        jTextFieldFechaFin = new javax.swing.JTextField();
        jLabelCupo = new javax.swing.JLabel();
        jTextFieldCupo = new javax.swing.JTextField();
        jButtonBuscarEdicion = new javax.swing.JButton();

        jLabelEdicionNombre.setText("Ediciones");

        jComboBoxEdiciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxEdiciones.setPreferredSize(new java.awt.Dimension(250, 26));

        jLabelNombre.setText("Nombre");

        jLabelCurso.setText("Curso");

        jLabelFechaFin.setText("Fecha de finalización");

        jLabelFechaInicio.setText("Fecha de inicio");

        jLabelDocente.setText("Docente(s)");

        jLabelEstudiantes.setText("Estudiantes inscriptos:");

        jScrollPaneEstudiantes.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jListEstudiantes.setPreferredSize(null);
        jListEstudiantes.setVisibleRowCount(6);
        jScrollPaneEstudiantes.setViewportView(jListEstudiantes);

        jLabelCupo.setText("Cupo");

        jTextFieldCupo.setText("30");

        jButtonBuscarEdicion.setText("Buscar");
        jButtonBuscarEdicion.addActionListener(this::jButtonBuscarEdicionActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelEstudiantes)
                                .addGap(36, 36, 36)
                                .addComponent(jLabelCupo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCupo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelEdicionNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCurso, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFechaFin, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCurso, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFechaInicio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDocente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDocente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxEdiciones, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPaneEstudiantes, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonBuscarEdicion)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelEdicionNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxEdiciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarEdicion))
                .addGap(18, 18, 18)
                .addComponent(jLabelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabelFechaInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelFechaFin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelDocente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEstudiantes)
                    .addComponent(jLabelCupo)
                    .addComponent(jTextFieldCupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneEstudiantes, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarEdicionActionPerformed
        int indice = jComboBoxEdiciones.getSelectedIndex();
        if (indice == -1) {
            return;
        }
        String nombreEdicion = (String) jComboBoxEdiciones.getSelectedItem();
        try {
            DataEdicionCurso edicion = edicionCursoPres.muestroEdicionCurso(nombreEdicion);
            jTextFieldNombre.setText(edicion.getNombreEdi());
            jTextFieldCurso.setText(edicion.getCursoAsoc().nombreCurso());
            jTextFieldFechaInicio.setText(edicion.getFechaInicio().toString());
            jTextFieldFechaFin.setText(edicion.getFechaFin().toString());
            if (edicion.getDocentes() != null && !edicion.getDocentes().isEmpty()) {
                StringBuilder nombresDocentes = new StringBuilder();
                for (DataDocente docente : edicion.getDocentes()) {
                    if (nombresDocentes.length() > 0) {
                        nombresDocentes.append(", ");
                    }
                nombresDocentes.append(docente.getNombre()).append(" ").append(docente.getApellido());
                }
                jTextFieldDocente.setText(nombresDocentes.toString());
            } else {
                jTextFieldDocente.setText("Sin docente");
            }
            jTextFieldCupo.setText(String.valueOf(edicion.getCupo()));
            //
            DefaultListModel<String> modelo = new DefaultListModel<>();
            for (DataInscEdicion inscripcion : edicion.getInscripciones()) {
                DataEstudiante estudiante = inscripcion.getEstudiante();
                modelo.addElement(estudiante.getNombre() + " " + estudiante.getApellido());
            }
            jListEstudiantes.setModel(modelo);
            SwingUtilities.invokeLater(() -> {jScrollPaneEstudiantes.getVerticalScrollBar().setValue(0);});
            //
            mostrarDatos();
        } catch (ErrorNoExiste e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonBuscarEdicionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarEdicion;
    private javax.swing.JComboBox<String> jComboBoxEdiciones;
    private javax.swing.JLabel jLabelCupo;
    private javax.swing.JLabel jLabelCurso;
    private javax.swing.JLabel jLabelDocente;
    private javax.swing.JLabel jLabelEdicionNombre;
    private javax.swing.JLabel jLabelEstudiantes;
    private javax.swing.JLabel jLabelFechaFin;
    private javax.swing.JLabel jLabelFechaInicio;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JList<String> jListEstudiantes;
    private javax.swing.JScrollPane jScrollPaneEstudiantes;
    private javax.swing.JTextField jTextFieldCupo;
    private javax.swing.JTextField jTextFieldCurso;
    private javax.swing.JTextField jTextFieldDocente;
    private javax.swing.JTextField jTextFieldFechaFin;
    private javax.swing.JTextField jTextFieldFechaInicio;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
