package com.grupo9.edext.grupo9.estacion_de_trabajo.gui;

import com.grupo9.edext.grupo9.estacion_de_trabajo.cliente.EdicionCursoPres;
import com.grupo9.edext.grupo9.servidor_central.controller.curso.Curso;
import com.grupo9.edext.grupo9.servidor_central.controller.edicion_de_curso.EdicionCurso;
import com.grupo9.edext.grupo9.servidor_central.controller.usuario.Estudiante;
import com.grupo9.edext.grupo9.mensajes.ErrorRepetidos;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;

public class InscribirAEdicionJInternalFrame extends javax.swing.JInternalFrame {
    private Curso cursoSeleccionado;
    private Estudiante[] estudiantes;
    private EdicionCurso[] ediciones;
    private final EdicionCursoPres edicionCursoPres = new EdicionCursoPres();
    
    public InscribirAEdicionJInternalFrame(Curso cursoSeleccionado) {
        initComponents();
        this.cursoSeleccionado = cursoSeleccionado;
        jSpinnerFechaInsc.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_MONTH));
        javax.swing.JSpinner.DateEditor editor1 = new javax.swing.JSpinner.DateEditor(jSpinnerFechaInsc, "dd/MM/yyyy");
        jSpinnerFechaInsc.setEditor(editor1);
        setTitle("Inscripción");
        setClosable(true);
        setResizable(true);
        setMaximizable(true);
        setIconifiable(true);
        cargarEdiciones();
        cargarEstudiantes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombreEdi = new javax.swing.JLabel();
        jComboBoxNombreEdi = new javax.swing.JComboBox<>();
        jLabelEstudiante = new javax.swing.JLabel();
        jComboBoxEdicionEstudiante = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jSpinnerFechaInsc = new javax.swing.JSpinner();
        jButtonGuardarInscripcion = new javax.swing.JButton();

        jLabelNombreEdi.setText("Edición");

        jComboBoxNombreEdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelEstudiante.setText("Estudiante");

        jComboBoxEdicionEstudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Fecha de inscripción:");

        jButtonGuardarInscripcion.setText("Inscribir");
        jButtonGuardarInscripcion.addActionListener(this::jButtonGuardarInscripcionActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonGuardarInscripcion))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelNombreEdi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxEdicionEstudiante, 0, 250, Short.MAX_VALUE)
                                    .addComponent(jComboBoxNombreEdi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinnerFechaInsc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 93, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxNombreEdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreEdi))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEstudiante)
                    .addComponent(jComboBoxEdicionEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jSpinnerFechaInsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButtonGuardarInscripcion)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void cargarEdiciones(){
        ediciones = edicionCursoPres.traerEdiciones(cursoSeleccionado);
        jComboBoxNombreEdi.removeAllItems();
        jComboBoxNombreEdi.addItem("Ninguno");
        for(EdicionCurso edicion : ediciones) {
            jComboBoxNombreEdi.addItem(edicion.getNombreEdi());
        }
    }
    
    private void cargarEstudiantes(){
        estudiantes = edicionCursoPres.traerEstudiantes();
        jComboBoxEdicionEstudiante.removeAllItems();
        jComboBoxEdicionEstudiante.addItem("Ninguno");
        for(Estudiante estudiante : estudiantes) {
            jComboBoxEdicionEstudiante.addItem(estudiante.getNombre() + " " + estudiante.getApellido());
        }
    }
    
    private void jButtonGuardarInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarInscripcionActionPerformed
        Date fecha0 = (Date) jSpinnerFechaInsc.getValue();
        LocalDate fechaInsc = fecha0.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        if (fechaInsc.isBefore(LocalDate.now())) {
            JOptionPane.showMessageDialog(this, "La fecha de inscripción debe ser actual o posterior al día de hoy.", "Datos inválidos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int indice = jComboBoxEdicionEstudiante.getSelectedIndex();
        int indice1 = jComboBoxNombreEdi.getSelectedIndex();
        if (indice <= 0 || indice1 <= 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una edición y un estudiante.", "Datos requeridos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Estudiante estudiante = estudiantes[indice- 1];
        EdicionCurso edicion = ediciones[indice1 - 1];
        try {
            edicionCursoPres.inscribirNuevoEstudianteEdicion(estudiante.getNickname(), edicion.getNombreEdi(), fechaInsc);
            JOptionPane.showMessageDialog(this, "Inscripción realizada con éxito!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } catch (ErrorRepetidos e) {
            JOptionPane.showMessageDialog(this, "El estudiante fue inscripto previamente.", "Inscripción duplicada", JOptionPane.WARNING_MESSAGE);        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se pudo realizar la inscripción.", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonGuardarInscripcionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardarInscripcion;
    private javax.swing.JComboBox<String> jComboBoxEdicionEstudiante;
    private javax.swing.JComboBox<String> jComboBoxNombreEdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelEstudiante;
    private javax.swing.JLabel jLabelNombreEdi;
    private javax.swing.JSpinner jSpinnerFechaInsc;
    // End of variables declaration//GEN-END:variables
}
