package com.grupo9.edext.grupo9.estacion_de_trabajo.gui;

import javax.swing.JPanel;
import java.util.ArrayList;
import com.grupo9.edext.grupo9.estacion_de_trabajo.cliente.ProgramaDeFormacion;

public class MainJFrame extends javax.swing.JFrame {

    private final ProgramaDeFormacion programaDeFormacion = new ProgramaDeFormacion();
    
    private final ArrayList<JPanel> allJPanels = new ArrayList<JPanel>();
    
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelCrearUsuario = new javax.swing.JPanel();
        jLabelCrearUsuario = new javax.swing.JLabel();
        JPanelConsultarUsuarios = new javax.swing.JPanel();
        jLabelConsultarUsuarios = new javax.swing.JLabel();
        JPanelCrearCurso = new javax.swing.JPanel();
        jLabelCrearCurso = new javax.swing.JLabel();
        JPanelConsultarCursos = new javax.swing.JPanel();
        jLabelConsultarCursos = new javax.swing.JLabel();
        JPanelCrearPrograma = new javax.swing.JPanel();
        jLabelCrearPrograma = new javax.swing.JLabel();
        jButtonGuardarPrograma = new javax.swing.JButton();
        jLabelCearProgramaNombre = new javax.swing.JLabel();
        jTextCrearProgramaNombre = new javax.swing.JTextField();
        jLabelCrearProgramaDesc = new javax.swing.JLabel();
        jTextAreaCrearProgramaDesc = new javax.swing.JTextArea();
        jLabelCrearProgramaFechaInicio = new javax.swing.JLabel();
        jFormattedTextFieldCrearProgramaFechaInicio = new javax.swing.JFormattedTextField();
        jLabelCrearProgramaFechaFin = new javax.swing.JLabel();
        jFormattedTextFieldCrearProgramaFechaFin = new javax.swing.JFormattedTextField();
        jLabelCrearProgramaCursos = new javax.swing.JLabel();
        choiceCrearProgramaCursos = new java.awt.Choice();
        jTableCrearProgramaCursos = new javax.swing.JTable();
        JPanelConsultarProgramas = new javax.swing.JPanel();
        jLabelConsultarProgramas = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUsuarios = new javax.swing.JMenu();
        jMenuItemCrearUsuario = new javax.swing.JMenuItem();
        jMenuItemConsultarUsuario = new javax.swing.JMenuItem();
        jMenuItemModificar = new javax.swing.JMenuItem();
        jMenuCursos = new javax.swing.JMenu();
        jMenuItemCrearCurso = new javax.swing.JMenuItem();
        jMenuItemConsultarCurso = new javax.swing.JMenuItem();
        jMenuProgDeFormacion = new javax.swing.JMenu();
        jMenuItemCrearProgDeFormacion = new javax.swing.JMenuItem();
        jMenuItemConsultarProgDeFormacion = new javax.swing.JMenuItem();
        jMenuItemAgregarProgDeFormacion = new javax.swing.JMenuItem();
        jMenuEdicionDeCurso = new javax.swing.JMenu();
        jMenuItemCrearEdicionCurso = new javax.swing.JMenuItem();
        jMenuItemConsultarEdicionCurso = new javax.swing.JMenuItem();
        jMenuItemInscripcionEdicionCurso = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabelCrearUsuario.setText("Crear Usuario");

        javax.swing.GroupLayout JPanelCrearUsuarioLayout = new javax.swing.GroupLayout(JPanelCrearUsuario);
        JPanelCrearUsuario.setLayout(JPanelCrearUsuarioLayout);
        JPanelCrearUsuarioLayout.setHorizontalGroup(
            JPanelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelCrearUsuarioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelCrearUsuario)
                .addContainerGap(686, Short.MAX_VALUE))
        );
        JPanelCrearUsuarioLayout.setVerticalGroup(
            JPanelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelCrearUsuarioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelCrearUsuario)
                .addContainerGap(549, Short.MAX_VALUE))
        );

        jLabelConsultarUsuarios.setText("Consultar Usuarios");

        javax.swing.GroupLayout JPanelConsultarUsuariosLayout = new javax.swing.GroupLayout(JPanelConsultarUsuarios);
        JPanelConsultarUsuarios.setLayout(JPanelConsultarUsuariosLayout);
        JPanelConsultarUsuariosLayout.setHorizontalGroup(
            JPanelConsultarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelConsultarUsuariosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelConsultarUsuarios)
                .addContainerGap(658, Short.MAX_VALUE))
        );
        JPanelConsultarUsuariosLayout.setVerticalGroup(
            JPanelConsultarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelConsultarUsuariosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelConsultarUsuarios)
                .addContainerGap(549, Short.MAX_VALUE))
        );

        jLabelCrearCurso.setText("Crear Curso");

        javax.swing.GroupLayout JPanelCrearCursoLayout = new javax.swing.GroupLayout(JPanelCrearCurso);
        JPanelCrearCurso.setLayout(JPanelCrearCursoLayout);
        JPanelCrearCursoLayout.setHorizontalGroup(
            JPanelCrearCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelCrearCursoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelCrearCurso)
                .addContainerGap(695, Short.MAX_VALUE))
        );
        JPanelCrearCursoLayout.setVerticalGroup(
            JPanelCrearCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelCrearCursoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelCrearCurso)
                .addContainerGap(549, Short.MAX_VALUE))
        );

        jLabelConsultarCursos.setText("Consultar Cursos");

        javax.swing.GroupLayout JPanelConsultarCursosLayout = new javax.swing.GroupLayout(JPanelConsultarCursos);
        JPanelConsultarCursos.setLayout(JPanelConsultarCursosLayout);
        JPanelConsultarCursosLayout.setHorizontalGroup(
            JPanelConsultarCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelConsultarCursosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelConsultarCursos)
                .addContainerGap(667, Short.MAX_VALUE))
        );
        JPanelConsultarCursosLayout.setVerticalGroup(
            JPanelConsultarCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelConsultarCursosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelConsultarCursos)
                .addContainerGap(549, Short.MAX_VALUE))
        );

        jLabelCrearPrograma.setText("Crear Programa");

        jButtonGuardarPrograma.setText("Guardar");
        jButtonGuardarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarProgramaActionPerformed(evt);
            }
        });

        jLabelCearProgramaNombre.setText("Nombre *");

        jTextCrearProgramaNombre.setText("nombre");

        jLabelCrearProgramaDesc.setText("Descripción *");

        jTextAreaCrearProgramaDesc.setColumns(20);
        jTextAreaCrearProgramaDesc.setRows(5);
        jTextAreaCrearProgramaDesc.setText("descripción");

        jLabelCrearProgramaFechaInicio.setText("Fecha de inicio");

        jFormattedTextFieldCrearProgramaFechaInicio.setText("01/01/2000");
        jFormattedTextFieldCrearProgramaFechaInicio.setMinimumSize(new java.awt.Dimension(110, 26));
        jFormattedTextFieldCrearProgramaFechaInicio.setName(""); // NOI18N
        jFormattedTextFieldCrearProgramaFechaInicio.setPreferredSize(new java.awt.Dimension(110, 26));

        jLabelCrearProgramaFechaFin.setText("Fecha de finalización");

        jFormattedTextFieldCrearProgramaFechaFin.setText("01/01/2000");
        jFormattedTextFieldCrearProgramaFechaFin.setMinimumSize(new java.awt.Dimension(110, 26));
        jFormattedTextFieldCrearProgramaFechaFin.setPreferredSize(new java.awt.Dimension(110, 26));

        jLabelCrearProgramaCursos.setText("Cursos");

        jTableCrearProgramaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));

        javax.swing.GroupLayout JPanelCrearProgramaLayout = new javax.swing.GroupLayout(JPanelCrearPrograma);
        JPanelCrearPrograma.setLayout(JPanelCrearProgramaLayout);
        JPanelCrearProgramaLayout.setHorizontalGroup(
            JPanelCrearProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelCrearProgramaLayout.createSequentialGroup()
                .addGroup(JPanelCrearProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JPanelCrearProgramaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTableCrearProgramaCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JPanelCrearProgramaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextAreaCrearProgramaDesc))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanelCrearProgramaLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(JPanelCrearProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCrearPrograma)
                            .addComponent(jLabelCrearProgramaDesc))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanelCrearProgramaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JPanelCrearProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanelCrearProgramaLayout.createSequentialGroup()
                                .addGroup(JPanelCrearProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCearProgramaNombre)
                                    .addComponent(jTextCrearProgramaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 376, Short.MAX_VALUE)
                                .addGroup(JPanelCrearProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextFieldCrearProgramaFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCrearProgramaFechaInicio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(JPanelCrearProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCrearProgramaFechaFin)
                                    .addComponent(jFormattedTextFieldCrearProgramaFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelCrearProgramaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonGuardarPrograma))
                            .addGroup(JPanelCrearProgramaLayout.createSequentialGroup()
                                .addGroup(JPanelCrearProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCrearProgramaCursos)
                                    .addComponent(choiceCrearProgramaCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        JPanelCrearProgramaLayout.setVerticalGroup(
            JPanelCrearProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelCrearProgramaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelCrearPrograma)
                .addGap(18, 18, 18)
                .addGroup(JPanelCrearProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelCrearProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextCrearProgramaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFormattedTextFieldCrearProgramaFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(JPanelCrearProgramaLayout.createSequentialGroup()
                            .addGroup(JPanelCrearProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelCearProgramaNombre)
                                .addComponent(jLabelCrearProgramaFechaFin))
                            .addGap(32, 32, 32)))
                    .addGroup(JPanelCrearProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jFormattedTextFieldCrearProgramaFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(JPanelCrearProgramaLayout.createSequentialGroup()
                            .addComponent(jLabelCrearProgramaFechaInicio)
                            .addGap(32, 32, 32))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCrearProgramaDesc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextAreaCrearProgramaDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCrearProgramaCursos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(choiceCrearProgramaCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTableCrearProgramaCursos, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonGuardarPrograma)
                .addContainerGap())
        );

        jLabelConsultarProgramas.setText("Consultar Programa");

        javax.swing.GroupLayout JPanelConsultarProgramasLayout = new javax.swing.GroupLayout(JPanelConsultarProgramas);
        JPanelConsultarProgramas.setLayout(JPanelConsultarProgramasLayout);
        JPanelConsultarProgramasLayout.setHorizontalGroup(
            JPanelConsultarProgramasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelConsultarProgramasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelConsultarProgramas)
                .addContainerGap(651, Short.MAX_VALUE))
        );
        JPanelConsultarProgramasLayout.setVerticalGroup(
            JPanelConsultarProgramasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelConsultarProgramasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelConsultarProgramas)
                .addContainerGap(549, Short.MAX_VALUE))
        );

        jMenuBar1.setToolTipText("");
        jMenuBar1.setAlignmentX(0.0F);

        jMenuUsuarios.setText("Usuarios");

        jMenuItemCrearUsuario.setText("Crear nuevo");
        jMenuItemCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearUsuarioActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemCrearUsuario);

        jMenuItemConsultarUsuario.setText("Consultar");
        jMenuItemConsultarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarUsuarioActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemConsultarUsuario);

        jMenuItemModificar.setText("Modificar datos");
        jMenuUsuarios.add(jMenuItemModificar);

        jMenuBar1.add(jMenuUsuarios);

        jMenuCursos.setText("Cursos");

        jMenuItemCrearCurso.setText("Crear nuevo");
        jMenuItemCrearCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearCursoActionPerformed(evt);
            }
        });
        jMenuCursos.add(jMenuItemCrearCurso);

        jMenuItemConsultarCurso.setText("Consultar");
        jMenuItemConsultarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarCursoActionPerformed(evt);
            }
        });
        jMenuCursos.add(jMenuItemConsultarCurso);

        jMenuBar1.add(jMenuCursos);

        jMenuProgDeFormacion.setText("Prog. de Formación");

        jMenuItemCrearProgDeFormacion.setText("Crear nuevo");
        jMenuItemCrearProgDeFormacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearProgDeFormacionActionPerformed(evt);
            }
        });
        jMenuProgDeFormacion.add(jMenuItemCrearProgDeFormacion);

        jMenuItemConsultarProgDeFormacion.setText("Consultar");
        jMenuItemConsultarProgDeFormacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarProgDeFormacionActionPerformed(evt);
            }
        });
        jMenuProgDeFormacion.add(jMenuItemConsultarProgDeFormacion);

        jMenuItemAgregarProgDeFormacion.setText("Agregar curso");
        jMenuProgDeFormacion.add(jMenuItemAgregarProgDeFormacion);

        jMenuBar1.add(jMenuProgDeFormacion);

        jMenuEdicionDeCurso.setText("Edición de Curso");

        jMenuItemCrearEdicionCurso.setText("Crear nueva Edición");
        jMenuEdicionDeCurso.add(jMenuItemCrearEdicionCurso);

        jMenuItemConsultarEdicionCurso.setText("Consultar");
        jMenuEdicionDeCurso.add(jMenuItemConsultarEdicionCurso);

        jMenuItemInscripcionEdicionCurso.setText("Inscribirse");
        jMenuEdicionDeCurso.add(jMenuItemInscripcionEdicionCurso);

        jMenuBar1.add(jMenuEdicionDeCurso);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JPanelCrearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JPanelCrearCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JPanelConsultarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JPanelConsultarCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JPanelCrearPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JPanelConsultarProgramas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JPanelCrearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JPanelCrearCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JPanelConsultarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JPanelConsultarCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JPanelCrearPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JPanelConsultarProgramas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearUsuarioActionPerformed
        showOnePanelAndHideTheRest(this.JPanelCrearUsuario);
    }//GEN-LAST:event_jMenuItemCrearUsuarioActionPerformed

    private void jMenuItemConsultarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarUsuarioActionPerformed
        showOnePanelAndHideTheRest(this.JPanelConsultarUsuarios);
    }//GEN-LAST:event_jMenuItemConsultarUsuarioActionPerformed

    private void jMenuItemCrearCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearCursoActionPerformed
        showOnePanelAndHideTheRest(this.JPanelCrearCurso);
    }//GEN-LAST:event_jMenuItemCrearCursoActionPerformed

    private void jMenuItemConsultarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarCursoActionPerformed
        showOnePanelAndHideTheRest(this.JPanelConsultarCursos);
    }//GEN-LAST:event_jMenuItemConsultarCursoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Walter: Agrega todos los paneles a una lista para que sea facil 
        // ocular todos los demas cuando queremos mostrar uno.
        this.allJPanels.add(JPanelCrearUsuario);
        this.allJPanels.add(JPanelConsultarUsuarios);
        this.allJPanels.add(JPanelCrearCurso);
        this.allJPanels.add(JPanelConsultarCursos);
        this.allJPanels.add(JPanelCrearPrograma);
        this.allJPanels.add(JPanelConsultarProgramas);
        this.hideAllJPanels();
        System.out.println("Window Opened");
    }//GEN-LAST:event_formWindowOpened

    private void jButtonGuardarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarProgramaActionPerformed
        programaDeFormacion.guardarNuevoProgramaDeFormacion();
    }//GEN-LAST:event_jButtonGuardarProgramaActionPerformed

    private void jMenuItemCrearProgDeFormacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearProgDeFormacionActionPerformed
        showOnePanelAndHideTheRest(this.JPanelCrearPrograma);
    }//GEN-LAST:event_jMenuItemCrearProgDeFormacionActionPerformed

    private void jMenuItemConsultarProgDeFormacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarProgDeFormacionActionPerformed
        showOnePanelAndHideTheRest(this.JPanelConsultarProgramas);
    }//GEN-LAST:event_jMenuItemConsultarProgDeFormacionActionPerformed

    private void hideAllJPanels() {
        for (JPanel panel : this.allJPanels) {
            panel.setVisible(false);
        }
    }
    
    private void showOnePanelAndHideTheRest(JPanel panelToShow){
        for (JPanel panel : this.allJPanels) {
            if (panel == panelToShow ){
                panel.setVisible(true);
            } else {
                panel.setVisible(false);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelConsultarCursos;
    private javax.swing.JPanel JPanelConsultarProgramas;
    private javax.swing.JPanel JPanelConsultarUsuarios;
    private javax.swing.JPanel JPanelCrearCurso;
    private javax.swing.JPanel JPanelCrearPrograma;
    private javax.swing.JPanel JPanelCrearUsuario;
    private java.awt.Choice choiceCrearProgramaCursos;
    private javax.swing.JButton jButtonGuardarPrograma;
    private javax.swing.JFormattedTextField jFormattedTextFieldCrearProgramaFechaFin;
    private javax.swing.JFormattedTextField jFormattedTextFieldCrearProgramaFechaInicio;
    private javax.swing.JLabel jLabelCearProgramaNombre;
    private javax.swing.JLabel jLabelConsultarCursos;
    private javax.swing.JLabel jLabelConsultarProgramas;
    private javax.swing.JLabel jLabelConsultarUsuarios;
    private javax.swing.JLabel jLabelCrearCurso;
    private javax.swing.JLabel jLabelCrearPrograma;
    private javax.swing.JLabel jLabelCrearProgramaCursos;
    private javax.swing.JLabel jLabelCrearProgramaDesc;
    private javax.swing.JLabel jLabelCrearProgramaFechaFin;
    private javax.swing.JLabel jLabelCrearProgramaFechaInicio;
    private javax.swing.JLabel jLabelCrearUsuario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCursos;
    private javax.swing.JMenu jMenuEdicionDeCurso;
    private javax.swing.JMenuItem jMenuItemAgregarProgDeFormacion;
    private javax.swing.JMenuItem jMenuItemConsultarCurso;
    private javax.swing.JMenuItem jMenuItemConsultarEdicionCurso;
    private javax.swing.JMenuItem jMenuItemConsultarProgDeFormacion;
    private javax.swing.JMenuItem jMenuItemConsultarUsuario;
    private javax.swing.JMenuItem jMenuItemCrearCurso;
    private javax.swing.JMenuItem jMenuItemCrearEdicionCurso;
    private javax.swing.JMenuItem jMenuItemCrearProgDeFormacion;
    private javax.swing.JMenuItem jMenuItemCrearUsuario;
    private javax.swing.JMenuItem jMenuItemInscripcionEdicionCurso;
    private javax.swing.JMenuItem jMenuItemModificar;
    private javax.swing.JMenu jMenuProgDeFormacion;
    private javax.swing.JMenu jMenuUsuarios;
    private javax.swing.JTable jTableCrearProgramaCursos;
    private javax.swing.JTextArea jTextAreaCrearProgramaDesc;
    private javax.swing.JTextField jTextCrearProgramaNombre;
    // End of variables declaration//GEN-END:variables
}
