package com.grupo9.edext.grupo9.estacion_de_trabajo.gui;

import com.grupo9.edext.grupo9.estacion_de_trabajo.cliente.UsuarioPres;
import com.grupo9.edext.grupo9.estacion_de_trabajo.cliente.InstitutoPres;

import com.grupo9.edext.grupo9.estacion_de_trabajo.gui.curso.ConsultarCursosJInternalFrame;
import com.grupo9.edext.grupo9.estacion_de_trabajo.gui.curso.CrearCursosJInternalFrame;
import com.grupo9.edext.grupo9.estacion_de_trabajo.gui.instituto.GestionarInstitutosJInternalFrame;
import com.grupo9.edext.grupo9.estacion_de_trabajo.gui.programa_de_formacion.ConsultarProgramasJInternalFrame;
import com.grupo9.edext.grupo9.estacion_de_trabajo.gui.programa_de_formacion.CrearProgramasJInternalFrame;
import com.grupo9.edext.grupo9.mensajes.ErrorNoExiste;
import com.grupo9.edext.grupo9.servidor_central.dominio.DataInstituto;
import java.awt.Component;
import java.beans.PropertyVetoException;
import javax.swing.*;
import java.util.ArrayList;
import java.time.LocalDate;
import java.util.HashSet;
import java.awt.BorderLayout;
import javax.swing.table.DefaultTableModel;

public class MainJFrame extends javax.swing.JFrame {
    
    private final UsuarioPres usuarioPres = new UsuarioPres();
    private final InstitutoPres institutoPres = new InstitutoPres();
    private java.io.File archivoImagenSeleccionado = null;
    private final ArrayList<JPanel> allJPanels = new ArrayList<JPanel>();
    private Component jScrollPaneTablaConsultaUsuarios;
    private final ArrayList<JInternalFrame> allJInternalFrame = new ArrayList<JInternalFrame>();
    
    public MainJFrame() {
        initComponents();
        setTitle("edEXT");
        setResizable(true);
        //alta usuario
        jSpinnerFechaNac.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_MONTH));
        javax.swing.JSpinner.DateEditor editor = new javax.swing.JSpinner.DateEditor(jSpinnerFechaNac, "dd/MM/yyyy");
        jSpinnerFechaNac.setEditor(editor);
        jComboBoxInstituto.setEnabled(false);
        //para que el panel azul ocupe hasta el borde
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(jDesktopPane1, BorderLayout.CENTER);
    }
    
    //al aparecer uno se cierra el otro
    private void mostrarInternalFrame(JInternalFrame frameToShow) {
        // cerrar todos los JPanel abiertos
        this.hideAllJPanels();
        //cerrar cualquier InternalFrame abierto
        JInternalFrame[] frames = jDesktopPane1.getAllFrames();
        for (JInternalFrame f : frames) {
            f.setVisible(false);
            f.dispose();
        }

        //agregar el nuevo InternalFrame
        jDesktopPane1.add(frameToShow);
        allJInternalFrame.add(frameToShow);

            frameToShow.setVisible(true);
            jDesktopPane1.revalidate();
            jDesktopPane1.repaint();
            frameToShow.revalidate();
            frameToShow.repaint();
        try {
            frameToShow.setSelected(true);
        } catch (PropertyVetoException e) {
            e.printStackTrace();
        }
    }
    
    private void cerrarInternalFrames() {
        for (JInternalFrame frame : jDesktopPane1.getAllFrames()) {
            frame.setVisible(false);
            frame.dispose();
        }
        jDesktopPane1.revalidate();
        jDesktopPane1.repaint();
    }
    
    private void abrirSeleccionCursoAlta(){
        SeleccionarCursoJInternalFrame seleccion = new SeleccionarCursoJInternalFrame(jDesktopPane1, OperacionCurso.ALTA_EDICION);
        mostrarInternalFrame(seleccion);
    }
    
    private void abrirSeleccionCursoConsulta(){
        SeleccionarCursoJInternalFrame seleccion = new SeleccionarCursoJInternalFrame(jDesktopPane1, OperacionCurso.CONSULTA_EDICION);
        mostrarInternalFrame(seleccion);
    }
    
    private void abrirSeleccionCursoInscripcion(){
        SeleccionarCursoJInternalFrame seleccion = new SeleccionarCursoJInternalFrame(jDesktopPane1, OperacionCurso.INSCRIPCION_EDICION);
        mostrarInternalFrame(seleccion);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupEstYDoc = new javax.swing.ButtonGroup();
        JPanelAltaUsuario = new javax.swing.JPanel();
        jLabelAltaUsuario = new javax.swing.JLabel();
        jTextFieldNickname = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jSpinnerFechaNac = new javax.swing.JSpinner();
        jRadioButtonDocente = new javax.swing.JRadioButton();
        jComboBoxInstituto = new javax.swing.JComboBox<>();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelNick = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelFechaNac = new javax.swing.JLabel();
        jLabelSeleccionarFoto = new javax.swing.JLabel();
        jLabelImagen = new javax.swing.JLabel();
        jRadioButtonDocente1 = new javax.swing.JRadioButton();
        JPanelConsultarUsuarios = new javax.swing.JPanel();
        jLabelConsultarUsuarios = new javax.swing.JLabel();
        jScrollPaneTablaConsultarUsuarios = new javax.swing.JScrollPane();
        jTableConsultarUsuarios = new javax.swing.JTable();
        jButtonConsUsRefresh = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUsuarios = new javax.swing.JMenu();
        jMenuItemCrearUsuario = new javax.swing.JMenuItem();
        jMenuItemConsultarUsuario = new javax.swing.JMenuItem();
        jMenuItemModificar = new javax.swing.JMenuItem();
        jMenuCursos = new javax.swing.JMenu();
        jMenuItemCrearCurso = new javax.swing.JMenuItem();
        jMenuItemConsultarCurso = new javax.swing.JMenuItem();
        jMenuProgDeFormacion = new javax.swing.JMenu();
        jMenuItemCrearProgDeFormacion = new javax.swing.JMenuItem();
        jMenuItemConsultarProgDeFormacion = new javax.swing.JMenuItem();
        jMenuEdicionDeCurso = new javax.swing.JMenu();
        jMenuItemCrearEdicionCurso = new javax.swing.JMenuItem();
        jMenuItemConsultarEdicionCurso = new javax.swing.JMenuItem();
        jMenuItemInscripcionEdicionCurso = new javax.swing.JMenuItem();
        jMenuInstitutos = new javax.swing.JMenu();
        jMenuItemGestionarInstitutos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabelAltaUsuario.setText("Crear Usuario");

        jTextFieldNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNicknameActionPerformed(evt);
            }
        });

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jTextFieldApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoActionPerformed(evt);
            }
        });

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        jSpinnerFechaNac.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerFechaNacStateChanged(evt);
            }
        });

        buttonGroupEstYDoc.add(jRadioButtonDocente);
        jRadioButtonDocente.setText("Docente");
        jRadioButtonDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDocenteActionPerformed(evt);
            }
        });

        jComboBoxInstituto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Instituto" }));

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelNick.setText("Nickname");

        jLabelNombre.setText("Nombre");

        jLabelApellido.setText("Apellido");

        jLabelEmail.setText("Email");

        jLabelFechaNac.setText("Fecha de Nacimiento");

        jLabelSeleccionarFoto.setForeground(new java.awt.Color(51, 51, 255));
        jLabelSeleccionarFoto.setText("Seleccionar Foto de Perfil");
        jLabelSeleccionarFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelSeleccionarFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSeleccionarFotoMouseClicked(evt);
            }
        });

        jLabelImagen.setText("Imagen");

        buttonGroupEstYDoc.add(jRadioButtonDocente1);
        jRadioButtonDocente1.setText("Estudiante");
        jRadioButtonDocente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDocente1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelAltaUsuarioLayout = new javax.swing.GroupLayout(JPanelAltaUsuario);
        JPanelAltaUsuario.setLayout(JPanelAltaUsuarioLayout);
        JPanelAltaUsuarioLayout.setHorizontalGroup(
            JPanelAltaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelAltaUsuarioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(JPanelAltaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAltaUsuario)
                    .addGroup(JPanelAltaUsuarioLayout.createSequentialGroup()
                        .addGroup(JPanelAltaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanelAltaUsuarioLayout.createSequentialGroup()
                                .addGroup(JPanelAltaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelNick, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(jLabelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(27, 27, 27)
                                .addGroup(JPanelAltaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNickname, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(jTextFieldEmail)))
                            .addGroup(JPanelAltaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(JPanelAltaUsuarioLayout.createSequentialGroup()
                                    .addComponent(jButtonAceptar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonCancelar))
                                .addComponent(jRadioButtonDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxInstituto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButtonDocente1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(JPanelAltaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanelAltaUsuarioLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabelSeleccionarFoto))
                            .addGroup(JPanelAltaUsuarioLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPanelAltaUsuarioLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabelFechaNac)
                                .addGap(36, 36, 36)
                                .addComponent(jSpinnerFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanelAltaUsuarioLayout.setVerticalGroup(
            JPanelAltaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelAltaUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelAltaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JPanelAltaUsuarioLayout.createSequentialGroup()
                        .addGroup(JPanelAltaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinnerFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFechaNac))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelSeleccionarFoto)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JPanelAltaUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabelAltaUsuario)
                        .addGap(37, 37, 37)
                        .addGroup(JPanelAltaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNick))
                        .addGap(18, 18, 18)
                        .addGroup(JPanelAltaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNombre))
                        .addGap(18, 18, 18)
                        .addGroup(JPanelAltaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelApellido))
                        .addGap(17, 17, 17)
                        .addGroup(JPanelAltaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonDocente1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonDocente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxInstituto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(JPanelAltaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAceptar)
                            .addComponent(jButtonCancelar))
                        .addGap(257, 257, 257))))
        );

        jLabelConsultarUsuarios.setText("Consultar Usuarios");

        jTableConsultarUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tipo de usuario", "Nickname", "Nombre", "Apellido", "Email", "FechaNac", "Imagen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPaneTablaConsultarUsuarios.setViewportView(jTableConsultarUsuarios);

        jButtonConsUsRefresh.setText("Refrescar");
        jButtonConsUsRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsUsRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelConsultarUsuariosLayout = new javax.swing.GroupLayout(JPanelConsultarUsuarios);
        JPanelConsultarUsuarios.setLayout(JPanelConsultarUsuariosLayout);
        JPanelConsultarUsuariosLayout.setHorizontalGroup(
            JPanelConsultarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelConsultarUsuariosLayout.createSequentialGroup()
                .addGroup(JPanelConsultarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelConsultarUsuariosLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabelConsultarUsuarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonConsUsRefresh))
                    .addGroup(JPanelConsultarUsuariosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPaneTablaConsultarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JPanelConsultarUsuariosLayout.setVerticalGroup(
            JPanelConsultarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelConsultarUsuariosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(JPanelConsultarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConsultarUsuarios)
                    .addComponent(jButtonConsUsRefresh))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneTablaConsultarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(403, 244));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenuBar1.setToolTipText("");
        jMenuBar1.setAlignmentX(0.0F);

        jMenuUsuarios.setText("Usuarios");

        jMenuItemCrearUsuario.setText("Crear nuevo");
        jMenuItemCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearUsuarioActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemCrearUsuario);

        jMenuItemConsultarUsuario.setText("Consultar");
        jMenuItemConsultarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarUsuarioActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemConsultarUsuario);

        jMenuItemModificar.setText("Modificar datos");
        jMenuItemModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModificarActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemModificar);

        jMenuBar1.add(jMenuUsuarios);

        jMenuCursos.setText("Cursos");

        jMenuItemCrearCurso.setText("Crear nuevo");
        jMenuItemCrearCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearCursoActionPerformed(evt);
            }
        });
        jMenuCursos.add(jMenuItemCrearCurso);

        jMenuItemConsultarCurso.setText("Consultar");
        jMenuItemConsultarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarCursoActionPerformed(evt);
            }
        });
        jMenuCursos.add(jMenuItemConsultarCurso);

        jMenuBar1.add(jMenuCursos);

        jMenuProgDeFormacion.setText("Prog. de Formación");

        jMenuItemCrearProgDeFormacion.setText("Crear nuevo");
        jMenuItemCrearProgDeFormacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearProgDeFormacionActionPerformed(evt);
            }
        });
        jMenuProgDeFormacion.add(jMenuItemCrearProgDeFormacion);

        jMenuItemConsultarProgDeFormacion.setText("Consultar");
        jMenuItemConsultarProgDeFormacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarProgDeFormacionActionPerformed(evt);
            }
        });
        jMenuProgDeFormacion.add(jMenuItemConsultarProgDeFormacion);

        jMenuBar1.add(jMenuProgDeFormacion);

        jMenuEdicionDeCurso.setText("Edición de Curso");

        jMenuItemCrearEdicionCurso.setText("Crear nueva");
        jMenuItemCrearEdicionCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearEdicionCursoActionPerformed(evt);
            }
        });
        jMenuEdicionDeCurso.add(jMenuItemCrearEdicionCurso);

        jMenuItemConsultarEdicionCurso.setText("Consultar");
        jMenuItemConsultarEdicionCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarEdicionCursoActionPerformed(evt);
            }
        });
        jMenuEdicionDeCurso.add(jMenuItemConsultarEdicionCurso);

        jMenuItemInscripcionEdicionCurso.setText("Inscribirse");
        jMenuItemInscripcionEdicionCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInscripcionEdicionCursoActionPerformed(evt);
            }
        });
        jMenuEdicionDeCurso.add(jMenuItemInscripcionEdicionCurso);

        jMenuBar1.add(jMenuEdicionDeCurso);

        jMenuInstitutos.setText("Institutos");

        jMenuItemGestionarInstitutos.setText("Gestionar");
        jMenuItemGestionarInstitutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestionarInstitutosActionPerformed(evt);
            }
        });
        jMenuInstitutos.add(jMenuItemGestionarInstitutos);

        jMenuBar1.add(jMenuInstitutos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JPanelAltaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JPanelConsultarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(108, Short.MAX_VALUE)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                    .addContainerGap(266, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 802, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JPanelAltaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JPanelConsultarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(253, Short.MAX_VALUE)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addContainerGap(148, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 634, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearUsuarioActionPerformed
        cerrarInternalFrames();
        showOnePanelAndHideTheRest(this.JPanelAltaUsuario);
        HashSet<DataInstituto> institutos = this.institutoPres.cargarInstitutos();
        jComboBoxInstituto.removeAllItems();
        jComboBoxInstituto.addItem("Seleccione un Instituto...");
        if (institutos != null) {
            for (DataInstituto inst : institutos) {
                jComboBoxInstituto.addItem(inst.nombreI());
            }
        }
        jComboBoxInstituto.setEnabled(jRadioButtonDocente.isSelected());
    }//GEN-LAST:event_jMenuItemCrearUsuarioActionPerformed

    private void jMenuItemConsultarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarUsuarioActionPerformed
        cerrarInternalFrames();
        showOnePanelAndHideTheRest(this.JPanelConsultarUsuarios);
    }//GEN-LAST:event_jMenuItemConsultarUsuarioActionPerformed

    private void jMenuItemCrearCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearCursoActionPerformed
        mostrarInternalFrame(new CrearCursosJInternalFrame());
    }//GEN-LAST:event_jMenuItemCrearCursoActionPerformed

    private void jMenuItemConsultarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarCursoActionPerformed
        mostrarInternalFrame(new ConsultarCursosJInternalFrame(this.jDesktopPane1));
    }//GEN-LAST:event_jMenuItemConsultarCursoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Walter: Agrega todos los paneles a una lista para que sea facil 
        // ocular todos los demas cuando queremos mostrar uno.
        this.allJPanels.add(JPanelAltaUsuario);
        this.allJPanels.add(JPanelConsultarUsuarios);
        this.hideAllJPanels();
        System.out.println("Window Opened");
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItemCrearProgDeFormacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearProgDeFormacionActionPerformed
        mostrarInternalFrame(new CrearProgramasJInternalFrame());
    }//GEN-LAST:event_jMenuItemCrearProgDeFormacionActionPerformed

    private void jMenuItemConsultarProgDeFormacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarProgDeFormacionActionPerformed
        mostrarInternalFrame(new ConsultarProgramasJInternalFrame());
    }//GEN-LAST:event_jMenuItemConsultarProgDeFormacionActionPerformed

    private void jTextCrearProgramaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCrearProgramaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCrearProgramaNombreActionPerformed

    private void jLabelSeleccionarFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSeleccionarFotoMouseClicked
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();

        // Filtrar para que solo permita elegir imágenes JPG o PNG
        javax.swing.filechooser.FileNameExtensionFilter filtro = new javax.swing.filechooser.FileNameExtensionFilter("Imágenes JPG y PNG", "jpg", "png");
        fileChooser.setFileFilter(filtro);

        int resultado = fileChooser.showOpenDialog(this);

        if (resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
            this.archivoImagenSeleccionado = fileChooser.getSelectedFile();
            String rutaImagen = this.archivoImagenSeleccionado.getAbsolutePath();

            javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(rutaImagen);

            int ancho = jLabelImagen.getWidth() > 0 ? jLabelImagen.getWidth() : 160;
            int alto = jLabelImagen.getHeight() > 0 ? jLabelImagen.getHeight() : 160;

            java.awt.Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(
                ancho,
                alto,
                java.awt.Image.SCALE_SMOOTH
            );

            jLabelImagen.setIcon(new javax.swing.ImageIcon(imagenEscalada));
            jLabelImagen.setText(""); // Quita el texto "Imagen"
        }
    }//GEN-LAST:event_jLabelSeleccionarFotoMouseClicked

    private void jSpinnerFechaNacStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerFechaNacStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinnerFechaNacStateChanged

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNicknameActionPerformed

    private void jMenuItemGestionarInstitutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestionarInstitutosActionPerformed
        mostrarInternalFrame(new GestionarInstitutosJInternalFrame());
    }//GEN-LAST:event_jMenuItemGestionarInstitutosActionPerformed

    private void jMenuItemCrearEdicionCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearEdicionCursoActionPerformed
        hideAllJPanels();
        abrirSeleccionCursoAlta();
    }//GEN-LAST:event_jMenuItemCrearEdicionCursoActionPerformed

    private void jMenuItemConsultarEdicionCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarEdicionCursoActionPerformed
        hideAllJPanels();
        abrirSeleccionCursoConsulta();
    }//GEN-LAST:event_jMenuItemConsultarEdicionCursoActionPerformed

    private void jMenuItemInscripcionEdicionCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInscripcionEdicionCursoActionPerformed
        hideAllJPanels();
        abrirSeleccionCursoInscripcion();
    }//GEN-LAST:event_jMenuItemInscripcionEdicionCursoActionPerformed
    
    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        String nick = jTextFieldNickname.getText().trim();
        String nombre = jTextFieldNombre.getText().trim();
        String apellido = jTextFieldApellido.getText().trim();
        String email = jTextFieldEmail.getText().trim();

        if (nick.isEmpty() || nombre.isEmpty() || apellido.isEmpty() || email.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor complete todos los campos obligatorios.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Obtener la fecha del JSpinner
        java.util.Date fechaUtil = (java.util.Date) jSpinnerFechaNac.getValue();
        LocalDate fechaNac = fechaUtil.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
        String rutaImg = (this.archivoImagenSeleccionado != null) ? this.archivoImagenSeleccionado.getAbsolutePath() : null;

        try {
            // Pedir la interfaz al controlador mediante la Fábrica
            com.grupo9.edext.grupo9.servidor_central.controller.usuario.IUsuario iu = 
                com.grupo9.edext.grupo9.miscelanea.Fabrica.getInstance().getIUsuario();

            if (jRadioButtonDocente.isSelected()) {
                String inst = (String) jComboBoxInstituto.getSelectedItem();
                if (inst == null || inst.equals("Instituto") || inst.equals("Seleccione un Instituto...") || inst.isEmpty()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar un Instituto para el docente.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
                    return;
                }
                iu.registrarDocente(nick, nombre, apellido, email, fechaNac, rutaImg, inst);
            } else {
                iu.registrarEstudiante(nick, nombre, apellido, email, fechaNac, rutaImg);
            }

            javax.swing.JOptionPane.showMessageDialog(this, "¡Usuario registrado y guardado en la base de datos con éxito!", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            limpiarFormularioAltaUsuario();

        } catch (com.grupo9.edext.grupo9.mensajes.ErrorRepetidos e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Usuario ya registrado", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jMenuItemModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModificarActionPerformed
        cerrarInternalFrames();
    }//GEN-LAST:event_jMenuItemModificarActionPerformed

    private void jButtonConsUsRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsUsRefreshActionPerformed
        System.out.println("[GUI] Consultar todos los Usuarios");
        String[] nicknames = usuarioPres.listarUsuarios();

        if (nicknames == null) {
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTableConsultarUsuarios.getModel();
        model.setRowCount(0);

        // 2. Recorres los nicknames y consultas los datos completos de cada uno
        for (String nick : nicknames) {
            try {
                com.grupo9.edext.grupo9.servidor_central.dominio.DataUsuario usuario;
                
                usuario = usuarioPres.consultarUsuario(nick);
                
                // 3. Determinas el tipo según la instancia o clase devuelta
                String tipo = (usuario instanceof com.grupo9.edext.grupo9.servidor_central.dominio.DataDocente) ? "Docente" : "Estudiante";
                Object[] usuarioObj = new Object[]{
                    tipo,
                    usuario.getNickname(),
                    usuario.getNombre(),
                    usuario.getApellido(),
                    usuario.getEmail(),
                    usuario.getFechaNac(),
                    usuario.getImagen()
                };
                model.addRow(usuarioObj);
            } catch (ErrorNoExiste ex) {
                System.getLogger(MainJFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
    }//GEN-LAST:event_jButtonConsUsRefreshActionPerformed

    private void jRadioButtonDocente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDocente1ActionPerformed
        jComboBoxInstituto.setEnabled(false);
        jComboBoxInstituto.setSelectedIndex(0);
    }//GEN-LAST:event_jRadioButtonDocente1ActionPerformed

    private void jRadioButtonDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDocenteActionPerformed
        jComboBoxInstituto.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonDocenteActionPerformed
    
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {
       limpiarFormularioAltaUsuario();
       hideAllJPanels();
    }

    private void limpiarFormularioAltaUsuario() {
        jTextFieldNickname.setText("");
        jTextFieldNombre.setText("");
        jTextFieldApellido.setText("");
        jTextFieldEmail.setText("");
        jSpinnerFechaNac.setValue(new java.util.Date());
        jRadioButtonDocente.setSelected(false);
        jComboBoxInstituto.setEnabled(false);
        if (jComboBoxInstituto.getItemCount() > 0) {
            jComboBoxInstituto.setSelectedIndex(0);
        }
        jLabelImagen.setIcon(null);
        jLabelImagen.setText("Imagen");
        this.archivoImagenSeleccionado = null;
    }

    // Configurar el JSpinner para que maneje fechas (muestra Día, Mes y Año)
    private void hideAllJPanels() {
        for (JPanel panel : this.allJPanels) {
            panel.setVisible(false);
        }
    }

    
    private void showOnePanelAndHideTheRest(JPanel panelToShow){
        for (JPanel panel : this.allJPanels) {
            if (panel == panelToShow ){
                panel.setVisible(true);
            } else {
                panel.setVisible(false);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelAltaUsuario;
    private javax.swing.JPanel JPanelConsultarUsuarios;
    private javax.swing.ButtonGroup buttonGroupEstYDoc;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConsUsRefresh;
    private javax.swing.JComboBox<String> jComboBoxInstituto;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelAltaUsuario;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelConsultarUsuarios;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFechaNac;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelNick;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelSeleccionarFoto;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCursos;
    private javax.swing.JMenu jMenuEdicionDeCurso;
    private javax.swing.JMenu jMenuInstitutos;
    private javax.swing.JMenuItem jMenuItemConsultarCurso;
    private javax.swing.JMenuItem jMenuItemConsultarEdicionCurso;
    private javax.swing.JMenuItem jMenuItemConsultarProgDeFormacion;
    private javax.swing.JMenuItem jMenuItemConsultarUsuario;
    private javax.swing.JMenuItem jMenuItemCrearCurso;
    private javax.swing.JMenuItem jMenuItemCrearEdicionCurso;
    private javax.swing.JMenuItem jMenuItemCrearProgDeFormacion;
    private javax.swing.JMenuItem jMenuItemCrearUsuario;
    private javax.swing.JMenuItem jMenuItemGestionarInstitutos;
    private javax.swing.JMenuItem jMenuItemInscripcionEdicionCurso;
    private javax.swing.JMenuItem jMenuItemModificar;
    private javax.swing.JMenu jMenuProgDeFormacion;
    private javax.swing.JMenu jMenuUsuarios;
    private javax.swing.JRadioButton jRadioButtonDocente;
    private javax.swing.JRadioButton jRadioButtonDocente1;
    private javax.swing.JScrollPane jScrollPaneTablaConsultarUsuarios;
    private javax.swing.JSpinner jSpinnerFechaNac;
    private javax.swing.JTable jTableConsultarUsuarios;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNickname;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
