/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.grupo9.edext.grupo9.estacion_de_trabajo.gui;

import javax.swing.JPanel;
import java.util.ArrayList;

/**
 *
 * @author Walter
 */
public class MainJFrame extends javax.swing.JFrame {

    ArrayList<JPanel> allJPanels = new ArrayList<JPanel>();
    
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelCrearUsuario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JPanelConsultarUsuarios = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        JPanelCrearCurso = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JPanelConsultarCursos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUsuarios = new javax.swing.JMenu();
        jMenuItemCrearUsuario = new javax.swing.JMenuItem();
        jMenuItemConsultarUsuario = new javax.swing.JMenuItem();
        jMenuCursos = new javax.swing.JMenu();
        jMenuItemCrearCurso = new javax.swing.JMenuItem();
        jMenuItemConsultarCurso = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Crear Usuario");

        javax.swing.GroupLayout JPanelCrearUsuarioLayout = new javax.swing.GroupLayout(JPanelCrearUsuario);
        JPanelCrearUsuario.setLayout(JPanelCrearUsuarioLayout);
        JPanelCrearUsuarioLayout.setHorizontalGroup(
            JPanelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelCrearUsuarioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(446, Short.MAX_VALUE))
        );
        JPanelCrearUsuarioLayout.setVerticalGroup(
            JPanelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelCrearUsuarioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(292, Short.MAX_VALUE))
        );

        jLabel3.setText("Consultar Usuarios");

        javax.swing.GroupLayout JPanelConsultarUsuariosLayout = new javax.swing.GroupLayout(JPanelConsultarUsuarios);
        JPanelConsultarUsuarios.setLayout(JPanelConsultarUsuariosLayout);
        JPanelConsultarUsuariosLayout.setHorizontalGroup(
            JPanelConsultarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelConsultarUsuariosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addContainerGap(418, Short.MAX_VALUE))
        );
        JPanelConsultarUsuariosLayout.setVerticalGroup(
            JPanelConsultarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelConsultarUsuariosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addContainerGap(292, Short.MAX_VALUE))
        );

        jLabel2.setText("Crear Curso");

        javax.swing.GroupLayout JPanelCrearCursoLayout = new javax.swing.GroupLayout(JPanelCrearCurso);
        JPanelCrearCurso.setLayout(JPanelCrearCursoLayout);
        JPanelCrearCursoLayout.setHorizontalGroup(
            JPanelCrearCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelCrearCursoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addContainerGap(455, Short.MAX_VALUE))
        );
        JPanelCrearCursoLayout.setVerticalGroup(
            JPanelCrearCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelCrearCursoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addContainerGap(292, Short.MAX_VALUE))
        );

        jLabel4.setText("Consultar Cursos");

        javax.swing.GroupLayout JPanelConsultarCursosLayout = new javax.swing.GroupLayout(JPanelConsultarCursos);
        JPanelConsultarCursos.setLayout(JPanelConsultarCursosLayout);
        JPanelConsultarCursosLayout.setHorizontalGroup(
            JPanelConsultarCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelConsultarCursosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addContainerGap(427, Short.MAX_VALUE))
        );
        JPanelConsultarCursosLayout.setVerticalGroup(
            JPanelConsultarCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelConsultarCursosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addContainerGap(292, Short.MAX_VALUE))
        );

        jMenuUsuarios.setText("Usuarios");

        jMenuItemCrearUsuario.setText("Crear nuevo");
        jMenuItemCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearUsuarioActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemCrearUsuario);

        jMenuItemConsultarUsuario.setText("Ver todos");
        jMenuItemConsultarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarUsuarioActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemConsultarUsuario);

        jMenuBar1.add(jMenuUsuarios);

        jMenuCursos.setText("Cursos");

        jMenuItemCrearCurso.setText("Crear nuevo");
        jMenuItemCrearCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearCursoActionPerformed(evt);
            }
        });
        jMenuCursos.add(jMenuItemCrearCurso);

        jMenuItemConsultarCurso.setText("Ver todos");
        jMenuItemConsultarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarCursoActionPerformed(evt);
            }
        });
        jMenuCursos.add(jMenuItemConsultarCurso);

        jMenuBar1.add(jMenuCursos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JPanelCrearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JPanelCrearCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JPanelConsultarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JPanelConsultarCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JPanelCrearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JPanelCrearCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JPanelConsultarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JPanelConsultarCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearUsuarioActionPerformed
        showOnePanelAndHideTheRest(this.JPanelCrearUsuario);
        System.out.println("Show Usuarios");
    }//GEN-LAST:event_jMenuItemCrearUsuarioActionPerformed

    private void jMenuItemConsultarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarUsuarioActionPerformed
        showOnePanelAndHideTheRest(this.JPanelConsultarUsuarios);
        System.out.println("Show Usuarios");
    }//GEN-LAST:event_jMenuItemConsultarUsuarioActionPerformed

    private void jMenuItemCrearCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearCursoActionPerformed
        showOnePanelAndHideTheRest(this.JPanelCrearCurso);
        System.out.println("Show Cursos");
    }//GEN-LAST:event_jMenuItemCrearCursoActionPerformed

    private void jMenuItemConsultarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarCursoActionPerformed
        showOnePanelAndHideTheRest(this.JPanelConsultarCursos);
        System.out.println("Show Cursos");
    }//GEN-LAST:event_jMenuItemConsultarCursoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Walter: Agrega todos los paneles a una lista para que sea facil 
        // ocular todos los demas cuando queremos mostrar uno.
        this.allJPanels.add(JPanelCrearUsuario);
        this.allJPanels.add(JPanelConsultarUsuarios);
        this.allJPanels.add(JPanelCrearCurso);
        this.allJPanels.add(JPanelConsultarCursos);
        this.hideAllJPanels();
        System.out.println("WindowOpened");
    }//GEN-LAST:event_formWindowOpened

    private void hideAllJPanels() {
        for (JPanel panel : this.allJPanels) {
            panel.setVisible(false);
        }
    }
    
    private void showOnePanelAndHideTheRest(JPanel panelToShow){
        for (JPanel panel : this.allJPanels) {
            if (panel == panelToShow ){
                panel.setVisible(true);
            } else {
                panel.setVisible(false);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelConsultarCursos;
    private javax.swing.JPanel JPanelConsultarUsuarios;
    private javax.swing.JPanel JPanelCrearCurso;
    private javax.swing.JPanel JPanelCrearUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCursos;
    private javax.swing.JMenuItem jMenuItemConsultarCurso;
    private javax.swing.JMenuItem jMenuItemConsultarUsuario;
    private javax.swing.JMenuItem jMenuItemCrearCurso;
    private javax.swing.JMenuItem jMenuItemCrearUsuario;
    private javax.swing.JMenu jMenuUsuarios;
    // End of variables declaration//GEN-END:variables
}
