package com.grupo9.edext.grupo9.estacion_de_trabajo.gui;

import com.grupo9.edext.grupo9.estacion_de_trabajo.gui.AltaEdicionJInternalFrame;
import com.grupo9.edext.grupo9.servidor_central.controller.curso.Curso;
import javax.swing.*;

public class SeleccionarCursoJInternalFrame extends javax.swing.JInternalFrame {
    private JDesktopPane jDesktopPane;
    
    public SeleccionarCursoJInternalFrame(JDesktopPane jDesktopPane) {
        initComponents();
        this.jDesktopPane = jDesktopPane;
        setTitle("Selección de Curso");
        setClosable(true);
        setResizable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSelectCurso = new javax.swing.JLabel();
        jLabelInstituto = new javax.swing.JLabel();
        jLabelCurso = new javax.swing.JLabel();
        jButtonSeleccionar = new javax.swing.JButton();
        jComboBoxCurso = new javax.swing.JComboBox<>();
        jComboBoxInstituto = new javax.swing.JComboBox<>();

        jLabelSelectCurso.setText("Selección de  Curso");

        jLabelInstituto.setText("Instituto");

        jLabelCurso.setText("Curso");

        jButtonSeleccionar.setText("Seleccionar");
        jButtonSeleccionar.addActionListener(this::jButtonSeleccionarActionPerformed);

        jComboBoxCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxInstituto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSeleccionar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCurso)
                                    .addComponent(jLabelInstituto))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxInstituto, 0, 178, Short.MAX_VALUE)
                                    .addComponent(jComboBoxCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabelSelectCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 129, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSelectCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInstituto)
                    .addComponent(jComboBoxInstituto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCurso)
                    .addComponent(jComboBoxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButtonSeleccionar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarActionPerformed
        Curso cursoSeleccionado = (Curso) jComboBoxCurso.getSelectedItem();
        AltaEdicionJInternalFrame alta = new AltaEdicionJInternalFrame(cursoSeleccionado);
        jDesktopPane.add(alta);
        alta.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonSeleccionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSeleccionar;
    private javax.swing.JComboBox<String> jComboBoxCurso;
    private javax.swing.JComboBox<String> jComboBoxInstituto;
    private javax.swing.JLabel jLabelCurso;
    private javax.swing.JLabel jLabelInstituto;
    private javax.swing.JLabel jLabelSelectCurso;
    // End of variables declaration//GEN-END:variables
}
