/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.grupo9.edext.grupo9.estacion_de_trabajo.gui.curso;

import com.grupo9.edext.grupo9.estacion_de_trabajo.cliente.CursoPres;
import com.grupo9.edext.grupo9.servidor_central.dominio.DataCurso;
import com.grupo9.edext.grupo9.servidor_central.dominio.DataInstituto;
import java.awt.Component;
import java.util.HashSet;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JCheckBox;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Walter
 */
public class CrearCursosJInternalFrame extends javax.swing.JInternalFrame {
    private final CursoPres cursoPres = new CursoPres();
    
    private final HashSet<DataCurso> cursosPreviosSeleccionados = new HashSet<>();
    
    /**
     * Creates new form GestionarCursosJInternalFrame
     */
    public CrearCursosJInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCrearCurso = new javax.swing.JLabel();
        jTextCrearCursoNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaCrearCursoDescripcion = new javax.swing.JTextArea();
        jLabelCrearCursoNombre = new javax.swing.JLabel();
        jLabelCrearCursoDescripcion = new javax.swing.JLabel();
        jTextCrearCursoDuracion = new javax.swing.JTextField();
        jLabelCrearCursoDuracion = new javax.swing.JLabel();
        jLabelCrearCursoCantHoras = new javax.swing.JLabel();
        jTextCrearCursoCantHoras = new javax.swing.JTextField();
        jLabelCrearCursoCantCreditos = new javax.swing.JLabel();
        jTextCrearCursoCantCreditos = new javax.swing.JTextField();
        jLabelCrearCursoUrl = new javax.swing.JLabel();
        jTextCrearCursoUrl = new javax.swing.JTextField();
        jButtonGuardarCurso = new javax.swing.JButton();
        jLabelCrearCursoPrevias = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListCrearCursoPrevias = new javax.swing.JList<>();
        jLabelCrearCursoInstituto = new javax.swing.JLabel();
        jComboBoxCrearCursoInstituto = new javax.swing.JComboBox<>();
        jButtonCancelarCurso = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jLabelCrearCurso.setText("Crear Curso");

        jTextAreaCrearCursoDescripcion.setColumns(20);
        jTextAreaCrearCursoDescripcion.setRows(5);
        jScrollPane1.setViewportView(jTextAreaCrearCursoDescripcion);

        jLabelCrearCursoNombre.setText("Nombre");

        jLabelCrearCursoDescripcion.setText("Descipción");

        jLabelCrearCursoDuracion.setText("Duración");

        jLabelCrearCursoCantHoras.setText("Cantidad de horas");

        jLabelCrearCursoCantCreditos.setText("Creditos");

        jLabelCrearCursoUrl.setText("Url");

        jButtonGuardarCurso.setText("Aceptar");
        jButtonGuardarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarCursoActionPerformed(evt);
            }
        });

        jLabelCrearCursoPrevias.setText("Previas");

        jScrollPane3.setViewportView(jListCrearCursoPrevias);
        jListCrearCursoPrevias.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jListCrearCursoPrevias.setCellRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index,
                boolean isSelected, boolean cellHasFocus) {
                JCheckBox checkBox = new JCheckBox();
                checkBox.setOpaque(true);
                if (value instanceof DataCurso dc) {
                    checkBox.setText(dc.nombreCurso());
                    checkBox.setSelected(cursosPreviosSeleccionados.contains(dc));
                }
                checkBox.setBackground(list.getBackground());
                checkBox.setForeground(list.getForeground());
                return checkBox;
            }
        });
        jListCrearCursoPrevias.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int index = jListCrearCursoPrevias.locationToIndex(evt.getPoint());
                if (index < 0 || !jListCrearCursoPrevias.getCellBounds(index, index).contains(evt.getPoint())) {
                    return;
                }
                DataCurso curso = jListCrearCursoPrevias.getModel().getElementAt(index);
                if (!cursosPreviosSeleccionados.add(curso)) {
                    cursosPreviosSeleccionados.remove(curso);
                }
                jListCrearCursoPrevias.clearSelection();
                jListCrearCursoPrevias.repaint();
            }
        });

        jLabelCrearCursoInstituto.setText("Instituto");

        jButtonCancelarCurso.setText("Cancelar");
        jButtonCancelarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelCrearCursoUrl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextCrearCursoCantHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelCrearCursoCantHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextCrearCursoCantCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelCrearCursoCantCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jTextCrearCursoUrl)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabelCrearCurso))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabelCrearCursoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jTextCrearCursoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextCrearCursoDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelCrearCursoDuracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(85, 85, 85)))))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelCrearCursoInstituto, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelCrearCursoPrevias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(118, 118, 118))
                                    .addComponent(jComboBoxCrearCursoInstituto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonCancelarCurso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonGuardarCurso))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCrearCursoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelCrearCurso)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCrearCursoDuracion)
                    .addComponent(jLabelCrearCursoNombre)
                    .addComponent(jLabelCrearCursoInstituto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCrearCursoDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCrearCursoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCrearCursoInstituto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCrearCursoCantHoras)
                            .addComponent(jLabelCrearCursoCantCreditos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextCrearCursoCantCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextCrearCursoCantHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addComponent(jLabelCrearCursoUrl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextCrearCursoUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCrearCursoPrevias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCrearCursoDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardarCurso)
                    .addComponent(jButtonCancelarCurso))
                .addContainerGap())
        );

        jComboBoxCrearCursoInstituto.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(
                JList<?> list,
                Object value,
                int index,
                boolean isSelected,
                boolean cellHasFocus) {

                super.getListCellRendererComponent(
                    list, value, index, isSelected, cellHasFocus);

                if (value instanceof DataInstituto di) {
                    setText(di.nombreI());
                }

                return this;
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarCursoActionPerformed
        final String nombre = jTextCrearCursoNombre.getText().trim();
        final String descripcion = jTextAreaCrearCursoDescripcion.getText().trim();

        if (nombre.isEmpty() || nombre.equals("") || descripcion.isEmpty() || descripcion.equals("")) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el nombre y la descripción del curso.", "Datos requeridos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        final int duracion;
        final int cantHoras;
        final int cantCreditos;
        try {
            duracion = Integer.parseInt(jTextCrearCursoDuracion.getText().trim());
            cantHoras = Integer.parseInt(jTextCrearCursoCantHoras.getText().trim());
            cantCreditos = Integer.parseInt(jTextCrearCursoCantCreditos.getText().trim());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "La duración, la cantidad de horas y los créditos deben ser números enteros.", "Datos inválidos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (duracion <= 0 || cantHoras <= 0 || cantCreditos <= 0) {
            JOptionPane.showMessageDialog(this, "La duración, la cantidad de horas y los créditos deben ser mayores que cero.", "Datos inválidos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        final String url = jTextCrearCursoUrl.getText().trim();
        if (url.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar la URL del curso.", "Dato requerido", JOptionPane.WARNING_MESSAGE);
            return;
        }

        final DataInstituto instituto = (DataInstituto) jComboBoxCrearCursoInstituto.getSelectedItem();
        if (instituto == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un instituto.", "Dato requerido", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (Boolean.TRUE.equals(cursoPres.existeCurso(nombre))) {
            JOptionPane.showMessageDialog(this, "Ya existe un curso con ese nombre. Prueba con otro nombre.", "Curso duplicado", JOptionPane.WARNING_MESSAGE);
            return;
        }

        final HashSet<DataCurso> previas = new HashSet<>(cursosPreviosSeleccionados);

        System.out.println("[GUI] Crear nuevo Curso: " + nombre);
        DataCurso nuevoCurso = cursoPres.guardarNuevoCurso(instituto, nombre, descripcion, duracion, cantHoras, cantCreditos, url, previas);
        if (nuevoCurso != null){
            this.limpiarFormularioCurso();
            javax.swing.JOptionPane.showMessageDialog(this, "Curso registrado y guardado con éxito", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo crear el curso. Verifique los datos ingresados.", "Error al crear curso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonGuardarCursoActionPerformed

    private void jButtonCancelarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarCursoActionPerformed
        this.limpiarFormularioCurso();
    }//GEN-LAST:event_jButtonCancelarCursoActionPerformed

    private void limpiarFormularioCurso() {
        jTextCrearCursoNombre.setText("");
        jTextAreaCrearCursoDescripcion.setText("");

        jTextCrearCursoDuracion.setText("");
        jTextCrearCursoCantHoras.setText("");
        jTextCrearCursoCantCreditos.setText("");

        jTextCrearCursoUrl.setText("");

        this.recargarCursosPrevias();
    }
    
    private void recargarCursosPrevias() {
        HashSet<DataCurso> cursos = cursoPres.cargarCursos();
        DefaultListModel<DataCurso> model = new DefaultListModel<>();

        if (cursos != null) {
            for (DataCurso curso : cursos) {
                model.addElement(curso);
            }
        }

        this.cursosPreviosSeleccionados.clear();
        jListCrearCursoPrevias.clearSelection();
        jListCrearCursoPrevias.setModel(model);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarCurso;
    private javax.swing.JButton jButtonGuardarCurso;
    private javax.swing.JComboBox<DataInstituto> jComboBoxCrearCursoInstituto;
    private javax.swing.JLabel jLabelCrearCurso;
    private javax.swing.JLabel jLabelCrearCursoCantCreditos;
    private javax.swing.JLabel jLabelCrearCursoCantHoras;
    private javax.swing.JLabel jLabelCrearCursoDescripcion;
    private javax.swing.JLabel jLabelCrearCursoDuracion;
    private javax.swing.JLabel jLabelCrearCursoInstituto;
    private javax.swing.JLabel jLabelCrearCursoNombre;
    private javax.swing.JLabel jLabelCrearCursoPrevias;
    private javax.swing.JLabel jLabelCrearCursoUrl;
    private javax.swing.JList<DataCurso> jListCrearCursoPrevias;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextAreaCrearCursoDescripcion;
    private javax.swing.JTextField jTextCrearCursoCantCreditos;
    private javax.swing.JTextField jTextCrearCursoCantHoras;
    private javax.swing.JTextField jTextCrearCursoDuracion;
    private javax.swing.JTextField jTextCrearCursoNombre;
    private javax.swing.JTextField jTextCrearCursoUrl;
    // End of variables declaration//GEN-END:variables
}
