/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.grupo9.edext.grupo9.estacion_de_trabajo.gui.programa_de_formacion;

import com.grupo9.edext.grupo9.estacion_de_trabajo.cliente.CursoPres;
import com.grupo9.edext.grupo9.estacion_de_trabajo.cliente.ProgramaDeFormacionPres;
import com.grupo9.edext.grupo9.servidor_central.dominio.DataCurso;
import com.grupo9.edext.grupo9.servidor_central.dominio.DataProgramaFormacion;
import java.awt.Component;
import java.awt.event.ItemEvent;
import java.util.HashSet;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Walter
 */
public class ConsultarProgramasJInternalFrame extends javax.swing.JInternalFrame {
    private final ProgramaDeFormacionPres programaDeFormacionPres = new ProgramaDeFormacionPres();
    private final CursoPres cursoPres = new CursoPres();

    /**
     * Creates new form ConsultarProgramasJInternalFrame
     */
    public ConsultarProgramasJInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelConsultarProgramas = new javax.swing.JLabel();
        jButtonConsultarProgramasRefresh = new javax.swing.JButton();
        jSubPanelTablaProgramasDeForm = new javax.swing.JPanel();
        jScrollPaneTablaConsultaProgramas = new javax.swing.JScrollPane();
        jTableConsultaProgramas = new javax.swing.JTable();
        jLabelSeccionDetallesDeProgSeleccionado = new javax.swing.JLabel();
        jLabelSeccionDetProgSelectNombre = new javax.swing.JLabel();
        jLabelSeccionDetProgSelectFechaCreado = new javax.swing.JLabel();
        jLabelSeccionDetProgSelectFechaIni = new javax.swing.JLabel();
        jLabelSeccionDetProgSelectFechaFin = new javax.swing.JLabel();
        jLabelSeccionDetProgSelectDesc = new javax.swing.JLabel();
        jLabelDetProgSelectNombre = new javax.swing.JLabel();
        jLabelDetProgSelectFechaCreado = new javax.swing.JLabel();
        jLabelDetProgSelectFechaIni = new javax.swing.JLabel();
        jLabelDetProgSelectFechaFin = new javax.swing.JLabel();
        jLabelDetProgSelectDesc = new javax.swing.JLabel();
        jLabelSeccionDetProgSelectCursos = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListDetProgSelectCursos = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListSeccionPdeFAgregarCursos = new javax.swing.JList<>();
        jLabelSeccionPdeFAgregarCursos = new javax.swing.JLabel();
        jCheckBoxAgregarCursoPrograma = new javax.swing.JCheckBox();
        jButtonConsultarProgAddCurso = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabelConsultarProgramas.setText("Consultar Programa");

        jButtonConsultarProgramasRefresh.setText("Refrescar");
        jButtonConsultarProgramasRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarProgramasRefreshActionPerformed(evt);
            }
        });

        jTableConsultaProgramas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableConsultaProgramas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultaProgramasMouseClicked(evt);
            }
        });
        jScrollPaneTablaConsultaProgramas.setViewportView(jTableConsultaProgramas);

        javax.swing.GroupLayout jSubPanelTablaProgramasDeFormLayout = new javax.swing.GroupLayout(jSubPanelTablaProgramasDeForm);
        jSubPanelTablaProgramasDeForm.setLayout(jSubPanelTablaProgramasDeFormLayout);
        jSubPanelTablaProgramasDeFormLayout.setHorizontalGroup(
            jSubPanelTablaProgramasDeFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSubPanelTablaProgramasDeFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneTablaConsultaProgramas)
                .addContainerGap())
        );
        jSubPanelTablaProgramasDeFormLayout.setVerticalGroup(
            jSubPanelTablaProgramasDeFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jSubPanelTablaProgramasDeFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneTablaConsultaProgramas, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabelSeccionDetallesDeProgSeleccionado.setText("Detalles del programa seleccionado");

        jLabelSeccionDetProgSelectNombre.setText("Nombre:");

        jLabelSeccionDetProgSelectFechaCreado.setText("Fecha de creación:");

        jLabelSeccionDetProgSelectFechaIni.setText("Fecha de Inicio:");

        jLabelSeccionDetProgSelectFechaFin.setText("Fecha de Finalización:");

        jLabelSeccionDetProgSelectDesc.setText("Descripción:");

        jLabelDetProgSelectNombre.setText("-");

        jLabelDetProgSelectFechaCreado.setText("-");

        jLabelDetProgSelectFechaIni.setText("-");

        jLabelDetProgSelectFechaFin.setText("-");

        jLabelDetProgSelectDesc.setText("-");
        jLabelDetProgSelectDesc.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelDetProgSelectDesc.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabelSeccionDetProgSelectCursos.setText("Cursos:");

        jListDetProgSelectCursos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(jListDetProgSelectCursos);
        jListDetProgSelectCursos.setCellRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index,
                boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof DataCurso dc) {
                    setText(dc.nombreCurso());
                }
                return this;
            }
        });

        jListSeccionPdeFAgregarCursos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListSeccionPdeFAgregarCursos.setEnabled(false);
        jScrollPane5.setViewportView(jListSeccionPdeFAgregarCursos);
        jListSeccionPdeFAgregarCursos.setCellRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index,
                boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof DataCurso dc) {
                    setText(dc.nombreCurso());
                }
                return this;
            }
        });

        jLabelSeccionPdeFAgregarCursos.setText("Agregar cursos:");

        jCheckBoxAgregarCursoPrograma.setText("Habilitar edición");
        jCheckBoxAgregarCursoPrograma.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxAgregarCursoProgramaItemStateChanged(evt);
            }
        });

        jButtonConsultarProgAddCurso.setText("Agregar");
        jButtonConsultarProgAddCurso.setEnabled(false);
        jButtonConsultarProgAddCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarProgAddCursoActionPerformed(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSubPanelTablaProgramasDeForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabelConsultarProgramas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonConsultarProgramasRefresh))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelSeccionDetProgSelectCursos)
                                    .addGap(325, 325, 325))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabelSeccionDetProgSelectFechaFin)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabelDetProgSelectFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabelSeccionDetProgSelectFechaIni)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabelDetProgSelectFechaIni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabelSeccionDetProgSelectFechaCreado)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabelDetProgSelectFechaCreado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabelSeccionDetProgSelectNombre)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabelDetProgSelectNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane4))
                            .addComponent(jLabelSeccionDetallesDeProgSeleccionado))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelSeccionDetProgSelectDesc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelDetProgSelectDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelSeccionPdeFAgregarCursos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                .addComponent(jCheckBoxAgregarCursoPrograma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonConsultarProgAddCurso)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConsultarProgramas)
                    .addComponent(jButtonConsultarProgramasRefresh))
                .addGap(18, 18, 18)
                .addComponent(jSubPanelTablaProgramasDeForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSeccionDetallesDeProgSeleccionado)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSeccionDetProgSelectNombre)
                            .addComponent(jLabelDetProgSelectNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSeccionDetProgSelectFechaCreado)
                            .addComponent(jLabelDetProgSelectFechaCreado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSeccionDetProgSelectFechaIni)
                            .addComponent(jLabelDetProgSelectFechaIni)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelSeccionDetProgSelectDesc)
                            .addGap(84, 84, 84))
                        .addComponent(jLabelDetProgSelectDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSeccionDetProgSelectFechaFin)
                            .addComponent(jLabelDetProgSelectFechaFin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSeccionDetProgSelectCursos)
                            .addComponent(jLabelSeccionPdeFAgregarCursos)
                            .addComponent(jCheckBoxAgregarCursoPrograma)))
                    .addComponent(jButtonConsultarProgAddCurso, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarProgramasRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarProgramasRefreshActionPerformed
        System.out.println("[GUI] Consultar todos los Programas");
        HashSet<DataProgramaFormacion> programas = this.programaDeFormacionPres.cargarProgramas();

        if(programas == null){
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTableConsultaProgramas.getModel();
        model.setRowCount(0);

        for(DataProgramaFormacion programa: programas){
            Object[] programaObj = new Object[]{programa.nombre(), programa.fechaInicio(), programa.fechaFin(), programa.descripcion()};
            model.addRow(programaObj);
        }
    }//GEN-LAST:event_jButtonConsultarProgramasRefreshActionPerformed

    private void jTableConsultaProgramasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultaProgramasMouseClicked
        JTable source = (JTable)evt.getSource();
        int row = source.rowAtPoint( evt.getPoint() );
        int column = source.columnAtPoint( evt.getPoint() );
        String seleccion = (String) source.getModel().getValueAt(row, column);

        //        JOptionPane.showMessageDialog(null, seleccion + "");
        if(seleccion != null){
            this.limpiarDetallesConsultaProgDeForm();
            this.actualizarListasCursosPrograma(seleccion);
            this.jCheckBoxAgregarCursoPrograma.setSelected(false);
            // Lista de todos los cursos disponibles para asociar al programa de formación
        } else {
            this.limpiarDetallesConsultaProgDeForm();
        }
    }//GEN-LAST:event_jTableConsultaProgramasMouseClicked

    private void jCheckBoxAgregarCursoProgramaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxAgregarCursoProgramaItemStateChanged
        String seleccion = this.obtenerProgDeFormSeleccionadoEnLaTablaDeConsulta();

        if(
            evt.getStateChange() == ItemEvent.SELECTED &&
            seleccion != null
        ){
            // Rellenar la lista de cursos que no están relacionados ya al programa
            HashSet<DataCurso> cursosDisponibles = this.cursoPres.cursosNoRelacionadosConUnProgDeFormacion(seleccion);

            DefaultListModel<DataCurso> mutableModelCurso = new DefaultListModel<>();
            this.jListSeccionPdeFAgregarCursos.setModel(mutableModelCurso);
            DefaultListModel<DataCurso> modelCurso = (DefaultListModel<DataCurso>) this.jListSeccionPdeFAgregarCursos.getModel();

            for(DataCurso curso: cursosDisponibles){
                modelCurso.addElement(curso);
            }

            this.jButtonConsultarProgAddCurso.setEnabled(true);
            this.jListSeccionPdeFAgregarCursos.setEnabled(true);
        } else {
            this.deshabilitarAgregarCursoDeProgDeForm();
        }
    }//GEN-LAST:event_jCheckBoxAgregarCursoProgramaItemStateChanged

    private void jButtonConsultarProgAddCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarProgAddCursoActionPerformed
        final DataCurso cursoSeleccionado = this.jListSeccionPdeFAgregarCursos.getSelectedValue();
        final String programaSeleccionado = this.obtenerProgDeFormSeleccionadoEnLaTablaDeConsulta();
        if(cursoSeleccionado != null && programaSeleccionado != null){
            Boolean guardado = this.programaDeFormacionPres.agregarCursoAProgramaDeFormacion(programaSeleccionado, cursoSeleccionado.nombreCurso());
            if (Boolean.TRUE.equals(guardado)) {
                this.actualizarListasCursosPrograma(programaSeleccionado);
            }
        }
    }//GEN-LAST:event_jButtonConsultarProgAddCursoActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        this.limpiarDetallesConsultaProgDeForm();
        this.jButtonConsultarProgramasRefreshActionPerformed(null);
    }//GEN-LAST:event_formInternalFrameOpened
    
    private String obtenerProgDeFormSeleccionadoEnLaTablaDeConsulta(){
        int row = this.jTableConsultaProgramas.getSelectedRow();
        int column = this.jTableConsultaProgramas.getSelectedColumn();
        String seleccion = null;
        if(row != -1 && column != -1){
            seleccion = (String) this.jTableConsultaProgramas.getModel().getValueAt(row, column);
            return seleccion;
        }
        return null;
    }
    
    private void actualizarListasCursosPrograma(String nombrePrograma) {
        DataProgramaFormacion programaSeleccionado = this.programaDeFormacionPres.buscarPorNombreId(nombrePrograma);
        if (programaSeleccionado == null) {
            this.limpiarDetallesConsultaProgDeForm();
            return;
        }

        jLabelDetProgSelectNombre.setText(programaSeleccionado.nombre());
        jLabelDetProgSelectFechaCreado.setText(programaSeleccionado.fechaDeCreacion().toString());
        jLabelDetProgSelectFechaIni.setText(programaSeleccionado.fechaInicio().toString());
        jLabelDetProgSelectFechaFin.setText(programaSeleccionado.fechaFin().toString());
        jLabelDetProgSelectDesc.setText(programaSeleccionado.descripcion());

        DefaultListModel<DataCurso> cursosProgramaModel = new DefaultListModel<>();
        for (DataCurso curso : programaSeleccionado.cursos()) {
            cursosProgramaModel.addElement(curso);
        }
        jListDetProgSelectCursos.setModel(cursosProgramaModel);

        DefaultListModel<DataCurso> cursosDisponiblesModel = new DefaultListModel<>();
        HashSet<DataCurso> cursosDisponibles = this.cursoPres.cursosNoRelacionadosConUnProgDeFormacion(nombrePrograma);
        if (cursosDisponibles != null) {
            for (DataCurso curso : cursosDisponibles) {
                cursosDisponiblesModel.addElement(curso);
            }
        }
        jListSeccionPdeFAgregarCursos.setModel(cursosDisponiblesModel);
    }
    
    private void limpiarDetallesConsultaProgDeForm(){
        this.jLabelDetProgSelectNombre.setText("-");
        this.jLabelDetProgSelectFechaCreado.setText("-");
        this.jLabelDetProgSelectFechaIni.setText("-");
        this.jLabelDetProgSelectFechaFin.setText("-");
        this.jLabelDetProgSelectDesc.setText("-");
        
//        DefaultListModel<DataCurso> model = (DefaultListModel<DataCurso>) this.jListDetProgSelectCursos.getModel();
        DefaultListModel<DataCurso> mutableModelCurso = new DefaultListModel<>();
        mutableModelCurso.clear();
        this.jListDetProgSelectCursos.setModel(mutableModelCurso);
        
        this.jCheckBoxAgregarCursoPrograma.setSelected(false);
    }
    
    private void deshabilitarAgregarCursoDeProgDeForm(){
//        DefaultListModel<DataCurso> model = (DefaultListModel<DataCurso>) this.jListSeccionPdeFAgregarCursos.getModel();
        DefaultListModel<DataCurso> mutableModelCurso = new DefaultListModel<>();
        mutableModelCurso.clear();
        this.jListSeccionPdeFAgregarCursos.setModel(mutableModelCurso);
        
        this.jButtonConsultarProgAddCurso.setEnabled(false);
        this.jListSeccionPdeFAgregarCursos.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultarProgAddCurso;
    private javax.swing.JButton jButtonConsultarProgramasRefresh;
    private javax.swing.JCheckBox jCheckBoxAgregarCursoPrograma;
    private javax.swing.JLabel jLabelConsultarProgramas;
    private javax.swing.JLabel jLabelDetProgSelectDesc;
    private javax.swing.JLabel jLabelDetProgSelectFechaCreado;
    private javax.swing.JLabel jLabelDetProgSelectFechaFin;
    private javax.swing.JLabel jLabelDetProgSelectFechaIni;
    private javax.swing.JLabel jLabelDetProgSelectNombre;
    private javax.swing.JLabel jLabelSeccionDetProgSelectCursos;
    private javax.swing.JLabel jLabelSeccionDetProgSelectDesc;
    private javax.swing.JLabel jLabelSeccionDetProgSelectFechaCreado;
    private javax.swing.JLabel jLabelSeccionDetProgSelectFechaFin;
    private javax.swing.JLabel jLabelSeccionDetProgSelectFechaIni;
    private javax.swing.JLabel jLabelSeccionDetProgSelectNombre;
    private javax.swing.JLabel jLabelSeccionDetallesDeProgSeleccionado;
    private javax.swing.JLabel jLabelSeccionPdeFAgregarCursos;
    private javax.swing.JList<DataCurso> jListDetProgSelectCursos;
    private javax.swing.JList<DataCurso> jListSeccionPdeFAgregarCursos;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPaneTablaConsultaProgramas;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel jSubPanelTablaProgramasDeForm;
    private javax.swing.JTable jTableConsultaProgramas;
    // End of variables declaration//GEN-END:variables
}
