/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.grupo9.edext.grupo9.estacion_de_trabajo.gui.programa_de_formacion;

import com.grupo9.edext.grupo9.estacion_de_trabajo.cliente.ProgramaDeFormacionPres;
import com.grupo9.edext.grupo9.servidor_central.dominio.DataProgramaFormacion;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;

/**
 *
 * @author Walter
 */
public class CrearProgramasJInternalFrame extends javax.swing.JInternalFrame {
    private final ProgramaDeFormacionPres programaDeFormacionPres = new ProgramaDeFormacionPres();

    /**
     * Creates new form GestionarProgramasJInternalFrame
     */
    public CrearProgramasJInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCrearPrograma = new javax.swing.JLabel();
        jButtonGuardarPrograma = new javax.swing.JButton();
        jLabelCearProgramaNombre = new javax.swing.JLabel();
        jTextCrearProgramaNombre = new javax.swing.JTextField();
        jLabelCrearProgramaDesc = new javax.swing.JLabel();
        jTextAreaCrearProgramaDesc = new javax.swing.JTextArea();
        jLabelCrearProgramaFechaInicio = new javax.swing.JLabel();
        jFormattedTextFieldCrearProgramaFechaInicio = new javax.swing.JFormattedTextField();
        jLabelCrearProgramaFechaFin = new javax.swing.JLabel();
        jFormattedTextFieldCrearProgramaFechaFin = new javax.swing.JFormattedTextField();
        jLabelCrearProgramaFechaInicio1 = new javax.swing.JLabel();
        jButtonCancelarPrograma = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabelCrearPrograma.setText("Crear Programa");

        jButtonGuardarPrograma.setText("Aceptar");
        jButtonGuardarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarProgramaActionPerformed(evt);
            }
        });

        jLabelCearProgramaNombre.setText("Nombre *");

        jLabelCrearProgramaDesc.setText("Descripción *");

        jTextAreaCrearProgramaDesc.setColumns(20);
        jTextAreaCrearProgramaDesc.setRows(5);

        jLabelCrearProgramaFechaInicio.setText("Fecha de inicio");

        jFormattedTextFieldCrearProgramaFechaInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jFormattedTextFieldCrearProgramaFechaInicio.setMinimumSize(new java.awt.Dimension(110, 26));
        jFormattedTextFieldCrearProgramaFechaInicio.setName(""); // NOI18N
        jFormattedTextFieldCrearProgramaFechaInicio.setPreferredSize(new java.awt.Dimension(110, 26));

        jLabelCrearProgramaFechaFin.setText("Fecha de finalización");

        jFormattedTextFieldCrearProgramaFechaFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jFormattedTextFieldCrearProgramaFechaFin.setMinimumSize(new java.awt.Dimension(110, 26));
        jFormattedTextFieldCrearProgramaFechaFin.setPreferredSize(new java.awt.Dimension(110, 26));

        jLabelCrearProgramaFechaInicio1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabelCrearProgramaFechaInicio1.setText("ej: 24/8/26");

        jButtonCancelarPrograma.setText("Cancelar");
        jButtonCancelarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarProgramaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCearProgramaNombre)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextCrearProgramaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                                .addComponent(jLabelCrearProgramaFechaInicio1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldCrearProgramaFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCrearProgramaFechaInicio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelCrearProgramaFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jFormattedTextFieldCrearProgramaFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCancelarPrograma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonGuardarPrograma))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCrearPrograma)
                            .addComponent(jLabelCrearProgramaDesc))
                        .addGap(0, 605, Short.MAX_VALUE))
                    .addComponent(jTextAreaCrearProgramaDesc))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelCrearPrograma)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCrearProgramaFechaInicio)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldCrearProgramaFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldCrearProgramaFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCrearProgramaFechaInicio1))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelCearProgramaNombre)
                                .addComponent(jLabelCrearProgramaFechaFin))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextCrearProgramaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCrearProgramaDesc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextAreaCrearProgramaDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardarPrograma)
                    .addComponent(jButtonCancelarPrograma))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarProgramaActionPerformed
        final String nombre = jTextCrearProgramaNombre.getText();
        final String descripcion = jTextAreaCrearProgramaDesc.getText();
        final LocalDate fechaInicio;
        final LocalDate fechaFin;
        
        if (nombre.isEmpty() || nombre.equals("")) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el nombre del curso.", "Dato requerido", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            fechaInicio = this.obtenerFechaComoLocalDate(jFormattedTextFieldCrearProgramaFechaInicio);
            fechaFin = this.obtenerFechaComoLocalDate(jFormattedTextFieldCrearProgramaFechaFin);
        } catch (java.text.ParseException | IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese fechas válidas con formato dd/MM/yyyy.", "Fecha inválida", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (fechaInicio == null || fechaFin == null) {
            JOptionPane.showMessageDialog(this, "Debe ingresar ambas fechas.", "Fecha requerida", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (fechaFin.isBefore(fechaInicio)) {
            JOptionPane.showMessageDialog(this, "La fecha de finalización no puede ser anterior a la fecha de inicio.", "Fechas inválidas", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (Boolean.TRUE.equals(programaDeFormacionPres.existeProgramaDeFormacion(nombre))) {
            JOptionPane.showMessageDialog(this, "Ya existe un programa de formación con ese nombre. Prueba con otro nombre.", "Programa duplicado", JOptionPane.WARNING_MESSAGE);
            return;
        }

        System.out.println("[GUI] Crear nuevo Programa: " + nombre + fechaInicio + fechaFin);
        DataProgramaFormacion nuevoPrograma = programaDeFormacionPres.guardarNuevoProgramaDeFormacion(nombre, descripcion, fechaInicio, fechaFin);
        if(nuevoPrograma != null){
            this.limpiarFormularioProgDeFormacion();
            JOptionPane.showMessageDialog(this, "Programa de formación registrado y guardado con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo crear el programa de formación. Verifique los datos ingresados.", "Error al crear programa", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonGuardarProgramaActionPerformed

    private void jButtonCancelarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarProgramaActionPerformed
        this.limpiarFormularioProgDeFormacion();
    }//GEN-LAST:event_jButtonCancelarProgramaActionPerformed

    private LocalDate obtenerFechaComoLocalDate(JFormattedTextField campo) throws java.text.ParseException {
        if (campo.getText().trim().isEmpty()) {
            return null;
        }

        campo.commitEdit();
        Object valor = campo.getValue();
        if (!(valor instanceof Date fecha)) {
            throw new IllegalArgumentException("El campo no contiene una fecha válida");
        }

        return fecha.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
    }

    private void limpiarFormularioProgDeFormacion() {
        jTextCrearProgramaNombre.setText("");
        jTextAreaCrearProgramaDesc.setText("");
        jFormattedTextFieldCrearProgramaFechaInicio.setValue(null);
        jFormattedTextFieldCrearProgramaFechaFin.setValue(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarPrograma;
    private javax.swing.JButton jButtonGuardarPrograma;
    private javax.swing.JFormattedTextField jFormattedTextFieldCrearProgramaFechaFin;
    private javax.swing.JFormattedTextField jFormattedTextFieldCrearProgramaFechaInicio;
    private javax.swing.JLabel jLabelCearProgramaNombre;
    private javax.swing.JLabel jLabelCrearPrograma;
    private javax.swing.JLabel jLabelCrearProgramaDesc;
    private javax.swing.JLabel jLabelCrearProgramaFechaFin;
    private javax.swing.JLabel jLabelCrearProgramaFechaInicio;
    private javax.swing.JLabel jLabelCrearProgramaFechaInicio1;
    private javax.swing.JTextArea jTextAreaCrearProgramaDesc;
    private javax.swing.JTextField jTextCrearProgramaNombre;
    // End of variables declaration//GEN-END:variables
}
